### ISSUE TITLE
Shared-tree fuzz tests with history on 0.1.1 fail

### ISSUE THREAD

**Issue by Abe27342** [microsoft/FluidFramework#10103]
## Describe the bug

With various minor code changes, shared-tree fuzz tests with history on 0.1.1 fail with errors similar to the following:

```text
Unexpected Errors in Logs:
[
  {
    "eventName": "fluid:telemetry:FluidDataStoreRuntime:SharedTree:EditChunkUploadFailure",
    "category": "error",
    "stack": "Error\n    at ContainerRuntime.<anonymous> (...\\FluidFramework\\packages\\runtime\\container-runtime\\dist\\blobManager.js:54:32)\n    at Object.onceWrapper (events.js:519:28)\n  
  at ContainerRuntime.emit (events.js:412:35)\n    at ContainerRuntime.dispose (...\\FluidFramework\\packages\\runtime\\container-runtime\\dist\\containerRuntime.js:767:14)\n    at ContainerContext.dispose (...\\FluidFramework\\packages\\loader\\container-loader\\dist\\containerContext.js:100:22)\n    at Container.close (...\\FluidFramework\\packages\\loader\\container-loader\\dist\\container.js:471:78)\n    at ContainerRuntime.<anonymous> (...\\FluidFramework\\packages\\loader\\container-loader\\dist\\container.js:1295:420)\n    at Summarizer.close (...\\FluidFramework\\packages\\runtime\\container-runtime\\dist\\summarizer.js:172:22)\n    at Summarizer.run (...\\FluidFramework\\packages\\runtime\\container-runtime\\dist\\summarizer.js:157:18)\n    at async Function.timedExecAsync (...\\FluidFramework\\packages\\utils\\telemetry-utils\\dist\\logger.js:334:25)",
    "error": "runtime disposed while blobAttach op in flight",
    "clientType": "noninteractive/summarizer",
    "containerId": "616591c6-acc5-4913-ae6c-ada0d066df8a",
    "docId": "test",
    "containerAttachState": "Attached",
    "containerLifecycleState": "closed",
    "containerConnectionState": "Disconnected",
    "runtimeVersion": "0.60.1000",
    "dataStoreId": "58d72261-09d7-49a6-9bfd-d6c464c94407",
    "isSharedTreeEvent": true,
    "dmInitialSeqNumber": 706,
    "dmLastProcessedSeqNumber": 772,
    "dmLastKnownSeqNumber": 772,
    "containerLoadedFromVersionId": "7f394579-eff7-473f-8c67-a98fbb9fad41",
    "dmLastMsqSeqNumber": 772,
    "dmLastMsqSeqTimestamp": 1651255391850,
    "dmLastMsqSeqClientId": null,
    "connectionStateDuration": 1.6895000040531158,
    "loaderId": "76b8a2bc-961a-4380-ac6b-2a8cf7a96878",
    "loaderVersion": "0.60.1000"
  }
]
```

### To Reproduce
1. Check out #10092
2. Revert the change to "adjustSeed" (i.e. set it back to 2)
3. Observe the "upgrade halfway through" test fails

@kian-thompson also reported a similar issue when touching the summarization heuristics.

### Expected behavior

Test passes

**Comment by taylorsw04** [comment]
@Abe27342 @noencke is this still relevant?

**Comment by Abe27342** [comment]
@noencke fixed this in #10242. Closing.
