### ISSUE TITLE
Prosemirror demo broken

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#11936]
Start the demo (local driver is fine) and try to load it in the browser - observe nothing renders and dev console has the following error:

```
fluid:telemetry:Container Request_cancel {"category":"error","duration":0,"error":"Adding different instances of a keyed plugin (plugin$)","clientType":"interactive","containerId":"0483bb8b-dc1b-4daf-b3d4-dfa53104c709","containerAttachState":"Detached","containerLifecycleState":"loaded","containerConnectionState":"Disconnected","serializedContainer":false,"dmInitialSeqNumber":0,"dmLastProcessedSeqNumber":0,"dmLastKnownSeqNumber":0,"connectionStateDuration":null,"loaderId":"1ede6d51-d2fb-49cd-acfd-e60f05b8f572","loaderVersion":"2.0.0-internal.1.2.0"} tick=5233 RangeError    at http://localhost:8080/dist/main.bundle.js:82020:48    at Array.forEach (<anonymous>)    at new Configuration (http://localhost:8080/dist/main.bundle.js:82019:24)    at Function.create (http://localhost:8080/dist/main.bundle.js:82176:21)    at new FluidCollabManager (http://localhost:8080/dist/main.bundle.js:38396:54)    at ProseMirror.<anonymous> (http://localhost:8080/dist/main.bundle.js:39328:35)    at Generator.next (<anonymous>)    at fulfilled (http://localhost:8080/dist/main.bundle.js:39210:58) +0ms
debug @ common.js:114
new:1 Uncaught (in promise) RangeError: Adding different instances of a keyed plugin (plugin$)
    at index.cjs:765:1
    at Array.forEach (<anonymous>)
    at new Configuration (index.cjs:764:1)
    at Function.create (index.cjs:921:1)
    at new FluidCollabManager (fluidCollabManager.ts:195:34)
    at ProseMirror.<anonymous> (prosemirror.ts:164:31)
    at Generator.next (<anonymous>)
    at fulfilled (prosemirror.ts:4:4)
```

**Comment by ChumpChief** [comment]
This was fixed by #12359
