### ISSUE TITLE
npm run start:spo fails with 401

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#11955]
Even after getkeys, forceReauth, and navigating to /odspLogin, trying `npm run start:spo` on any webpack-fluid-loader demo (e.g. diceroller) fails with a 401 error.  `npm run start:spo-df` works fine.

```
fetch.ts:16          GET https://microsoft-my.sharepoint-df.com/_api/v2.1/drive/root%3A/r11s/%3A 401
fetch @ fetch.ts:16
(anonymous) @ odspRequest.ts:16
(anonymous) @ odspRequest.ts:59
safeRequestCore @ odspRequest.ts:66
(anonymous) @ odspRequest.ts:59
authRequestWithRetry @ odspAuth.ts:152
authRequest @ odspRequest.ts:57
getAsync @ odspRequest.ts:16
getDriveItem @ odspDrives.ts:145
getDriveItemByRootFileName @ odspDrives.ts:75
createCreateNewRequest @ odspUrlResolver.ts:63
createRequestForCreateNew @ multiResolver.ts:127
attachContainer @ loader.ts:445
start @ loader.ts:331
await in start (async)
(anonymous) @ new:19
odspErrorUtils.ts:192 Uncaught (in promise) Error: Unable to get drive/item id from path
    at createOdspNetworkError (odspErrorUtils.ts:192:25)
    at throwOdspNetworkError (odspErrorUtils.ts:300:26)
    at getDriveItem (odspDrives.ts:149:34)
    at async OdspUrlResolver.createCreateNewRequest (odspUrlResolver.ts:63:27)
    at async attachContainer (loader.ts:445:11)
    at async Object.start (loader.ts:331:22)
```

Prior to the 401, I'm seeing a 308 redirect from `https://microsoft-my.sharepoint.com//_api/v2.1/drive/root:/r11s/:` to `https://microsoft-my.sharepoint-df.com/_api/v2.1/drive/root:/r11s/:` (note the df) which is the url that actually 401s.  This seems odd to me, not sure if expected.

End result is none of the demos using webpack-fluid-loader work with spo currently.

**Comment by ChumpChief** [comment]
I believe this is technically by-design, and one of these two commands will work depending on whether the user is in dogfood or not.  Confusing, but doesn't seem to be a bug at the moment.
