### ISSUE TITLE
Loading existing container from Tinylicious causes exception TypeError: boolean false is not iterable 

### ISSUE THREAD

**Issue by milanro** [microsoft/FluidFramework#12029]
## Describe the bug
I am developing at the branch based on the version 792e82651ec9208240d50fda2b8963dfb7442d17. I am using tinylicious@latest server for development. The loading of existing containers now fails with the following exception (it worked 2 days ago) :

`common.js:113 fluid:telemetry:Container ContainerClose {"category":"error","error":"boolean false is not iterable (cannot read property Symbol(Symbol.iterator))","errorType":"genericError","fluidErrorCode":"-","untrustedOrigin":1,"message":"boolean false is not iterable (cannot read property Symbol(Symbol.iterator))","errorInstanceId":"f9de8798-3abb-4f50-a2f1-59eec882abee","clientType":"interactive","containerId":"e157c712-e833-42e7-9d0b-01ffbd9cf12e","docId":"e5c83703-ab54-4d6f-92bc-cd8be0d682dd","containerAttachState":"Attached","containerLifecycleState":"loading","containerConnectionState":"Disconnected","dmInitialSeqNumber":0,"dmLastProcessedSeqNumber":0,"dmLastKnownSeqNumber":0,"containerLoadedFromVersionId":"d957e49bf444f76a9d567a61b808008849d4d1b4","containerLoadedFromVersionDate":"2022-09-19T15:42:59.000Z","connectionStateDuration":423.6000000014901,"loaderId":"a2d3e533-12c5-4758-a634-f42f2303f9b9","loaderVersion":"1.2.5"} tick=1631 Error    `

```
at new Map (<anonymous>)    
at new QuorumProposals (http://localhost:8080/app.5e20c86f3841e0a4488e.js:44841:23)    
at new Quorum (http://localhost:8080/app.5e20c86f3841e0a4488e.js:45035:32)    
at new ProtocolOpHandler (http://localhost:8080/app.5e20c86f3841e0a4488e.js:44640:24)    
at new ProtocolOpHandlerWithClientValidation (http://localhost:8080/app.5e20c86f3841e0a4488e.js:44710:1)    
at Container.initializeProtocolState (http://localhost:8080/app.5e20c86f3841e0a4488e.js:5706:26)    
at Container.initializeProtocolStateFromSnapshot (http://localhost:8080/app.5e20c86f3841e0a4488e.js:5702:44)    
at async Container.load (http://localhost:8080/app.5e20c86f3841e0a4488e.js:5573:15) +0ms
debug @ common.js:113
```

```
app.js:41 TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Map (<anonymous>)
    at new QuorumProposals (quorum.js:93:1)
    at new Quorum (quorum.js:287:1)
    at new ProtocolOpHandler (protocol.js:31:1)
    at new ProtocolOpHandlerWithClientValidation (protocol.js:101:8)
    at Container.initializeProtocolState (container.js:924:1)
    at Container.initializeProtocolStateFromSnapshot (container.js:920:1)
    at async Container.load (container.js:791:1)
```

This problem is reproducible even with the FluidHelloWorld application at https://fluidframework.com/docs/start/quick-start/

### To Reproduce
1. git clone https://github.com/microsoft/FluidHelloWorld.git
2. cd FluidHelloWorld
3. npm install
4. npm start
5. open in browser http://localhost:8080
6. you will get in browser the url  http://localhost:8080/#<container-id>
7. roll the dice
8. open in browser  http://localhost:8080/#<container-id> obtained at 6.
9. Check the logs for an exception

@DLehenbauer @vladsud @skylerjokiel @dstanesc do you see the same issue?

**Comment by milanro** [comment]
It looks like the summarize is not invoked anymore. Tested at f4a7c43b7db6ca9d4cfc0645c06bf8a1d7e82a5c.

**Comment by milanro** [comment]
This looks to happen to other applications either.
