### ISSUE TITLE
Fluid Quickstart fails first try

### ISSUE THREAD

**Issue by BobGerman** [microsoft/FluidFramework#12032]
## Describe the bug
I followed the Flud Quickstart. The first browser seems to work OK but any additional browsers accessing the URL fail with JavaScript errors (below)

### To Reproduce
1. Ensure node 14.x is installed
2. Clone https://github.com/microsoft/FluidHelloWorld.git
3. npm install
4. npm start
5. Browse to http://localhost:8080 - see the dice
6. Copy the browser URL to a new browser window; instead of seeing the dice, you get an error

### Expected behavior
I expected the app to work as described in the quick start
https://fluidframework.com/docs/start/quick-start/

### Logs
Here is the console log on the 2nd browser window:

common.js:113 fluid:telemetry:Container ContainerClose {"category":"error","error":"boolean false is not iterable (cannot read property Symbol(Symbol.iterator))","errorType":"genericError","fluidErrorCode":"-","untrustedOrigin":1,"message":"boolean false is not iterable (cannot read property Symbol(Symbol.iterator))","errorInstanceId":"d4a4a0f9-45ad-4581-b999-e466c55080e7","clientType":"interactive","containerId":"16f4ec4b-51ba-48e5-8b73-e3d910286451","docId":"6d2771ad-1f9d-4043-a588-bc6fb2abfa02","containerAttachState":"Attached","containerLifecycleState":"loading","containerConnectionState":"Disconnected","dmInitialSeqNumber":0,"dmLastProcessedSeqNumber":0,"dmLastKnownSeqNumber":0,"containerLoadedFromVersionId":"d2378bd824f5046359c12e74489fa182a3012d75","containerLoadedFromVersionDate":"2022-09-19T16:58:57.000Z","connectionStateDuration":80.1999999997206,"loaderId":"de883934-43d0-46bf-aced-5637b6d8eb3e","loaderVersion":"1.2.5"} tick=418 Error    at new Map (<anonymous>)    at new QuorumProposals (http://localhost:8080/app.cfb750c78f8f2b246e76.js:44841:23)    at new Quorum (http://localhost:8080/app.cfb750c78f8f2b246e76.js:45035:32)    at new ProtocolOpHandler (http://localhost:8080/app.cfb750c78f8f2b246e76.js:44640:24)    at new ProtocolOpHandlerWithClientValidation (http://localhost:8080/app.cfb750c78f8f2b246e76.js:44710:1)    at Container.initializeProtocolState (http://localhost:8080/app.cfb750c78f8f2b246e76.js:5706:26)    at Container.initializeProtocolStateFromSnapshot (http://localhost:8080/app.cfb750c78f8f2b246e76.js:5702:44)    at async Container.load (http://localhost:8080/app.cfb750c78f8f2b246e76.js:5573:15) +0ms
debug @ common.js:113
app.js:41 TypeError: boolean false is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Map (<anonymous>)
    at new QuorumProposals (quorum.js:93:1)
    at new Quorum (quorum.js:287:1)
    at new ProtocolOpHandler (protocol.js:31:1)
    at new ProtocolOpHandlerWithClientValidation (protocol.js:101:8)
    at Container.initializeProtocolState (container.js:924:1)
    at Container.initializeProtocolStateFromSnapshot (container.js:920:1)
    at async Container.load (container.js:791:1)

**Comment by BobGerman** [comment]
Fixed by @anthony-murphy
