### ISSUE TITLE
SummaryTreeUploadManager.writeSummaryBlob fails on IsoBuffer binary input.

### ISSUE THREAD

**Issue by milanro** [microsoft/FluidFramework#12509]
The `summaryTreeUploadManager.js` is located at 
`@fluidframework/server-services-client/lib/summaryTreeUploadManager.js` 
or within the sources at
`server/routerlicious/packages/services-client/src/summaryTreeUploadManager.ts`
 
It contains method `writeSummaryBlob`.
When the parameter ( `content` ) of this method is binary ( `IsoBuffer` ), I am getting assertion error at
`assert(hash === blob.sha, 0x0b6 /* "Blob.sha and hash do not match!!" */);`

```
at assert (http://localhost:8080/main.c853fa87a9f11f4da00a.js:33413:15)    
at SummaryTreeUploadManager.writeSummaryBlob (http://localhost:8080/main.c853fa87a9f11f4da00a.js:47567:81)    
at async http://localhost:8080/main.c853fa87a9f11f4da00a.js:47525:32    
at async Promise.all (index 0)    at async SummaryTreeUploadManager.writeSummaryTreeCore (http://localhost:8080/main.c853fa87a9f11f4da00a.js:47523:25)    
at async http://localhost:8080/main.c853fa87a9f11f4da00a.js:47525:32    
at async Promise.all (index 1)    
at async SummaryTreeUploadManager.writeSummaryTreeCore (http://localhost:8080/main.c853fa87a9f11f4da00a.js:47523:25)   
at async http://localhost:8080/main.c853fa87a9f11f4da00a.js:47525:32    
at async Promise.all (index 0) +0ms
```

In my case there are following different values of hashes :

```
blob.sha: "10ca28f96582596d5b15b0c920476f47241cb348"
hash    : "d2a6debdf8936e9d80c39d57f4827268be0b7b7e"
```
Attached are the files containing the IsoBuffer content and the base64 version generated within the `writeSummaryBlob` method :
[failing-base64.txt](https://github.com/microsoft/FluidFramework/files/9799083/failing-base64.txt)
[failing-content.txt](https://github.com/microsoft/FluidFramework/files/9799084/failing-content.txt)

@vladsud @DLehenbauer @dstanesc please, comment.

**Comment by milanro** [comment]
> Assert 0x0b6 originates from SummaryTreeUploadManager.ts:
> 
> ```ts
>     private async writeSummaryBlob(content: string | Uint8Array): Promise<string> {
>         const { parsedContent, encoding } = typeof content === "string"
>             ? { parsedContent: content, encoding: "utf-8" }
>             : { parsedContent: Uint8ArrayToString(content, "base64"), encoding: "base64" };
> 
>         // The gitHashFile would return the same hash as returned by the server as blob.sha
>         const hash = await gitHashFile(IsoBuffer.from(parsedContent, encoding));
>         if (!this.blobsShaCache.has(hash)) {
>             this.blobsShaCache.set(hash, "");
>             const blob = await this.manager.createBlob(parsedContent, encoding);
>             assert(hash === blob.sha, 0x0b6 /* "Blob.sha and hash do not match!!" */);
>         }
>         return hash;
>     }
> ```
> 
> Invoking SummaryTreeUploadManager implies that 'enableWholeSummaryUpload' has been disabled (i.e., the repo uses shredded summaries rather than whole document summaries.)
