### ISSUE TITLE
Can not Start Example given at https://github.com/microsoft/FluidHelloWorld.git

### ISSUE THREAD

**Issue by aum-app** [microsoft/FluidFramework#21885]
## Describe the bug

Example at: https://github.com/microsoft/FluidHelloWorld.git

Can not start app
### To Reproduce

do 'npm install' and then try npm start

### Expected behavior

It should have run after executing npm start

### Logs

[

$ npm run start

> @fluid-example/hello-world@0.1.0 start
> start-server-and-test start:server 7070 start:client

node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module 'map-stream'
Require stack:
- C:\Users\mrraj\Documents\Projects\FluidHelloWorld\node_modules\event-stream\index.js
- C:\Users\mrraj\Documents\Projects\FluidHelloWorld\node_modules\ps-tree\index.js
- C:\Users\mrraj\Documents\Projects\FluidHelloWorld\node_modules\start-server-and-test\src\index.js
- C:\Users\mrraj\Documents\Projects\FluidHelloWorld\node_modules\start-server-and-test\src\bin\start.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\mrraj\Documents\Projects\FluidHelloWorld\node_modules\event-stream\index.js:12:11)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\mrraj\Documents\Projects\FluidHelloWorld\node_modules\ps-tree\index.js:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\mrraj\\Documents\\Projects\\FluidHelloWorld\\node_modules\\event-stream\\index.js',
    'C:\\Users\\mrraj\\Documents\\Projects\\FluidHelloWorld\\node_modules\\ps-tree\\index.js',
    'C:\\Users\\mrraj\\Documents\\Projects\\FluidHelloWorld\\node_modules\\start-server-and-test\\src\\index.js',
    'C:\\Users\\mrraj\\Documents\\Projects\\FluidHelloWorld\\node_modules\\start-server-and-test\\src\\bin\\start.js'
  ]
}

Node.js v20.15.0

**Comment by nmsimons** [comment]
Thanks for the report. I can't currently repro the issue. I assume the npm install completed with no issues. Can you confirm and also include the dev environment you are using? Thanks! In the meantime, I will follow up with a few folks on the team.
