### ISSUE TITLE
Fluid-fetch tool fails to load files from office.com

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3539]
Leveraging fluid-fetch tool to download file from office.com results in this error:

ERROR: AssertionError [ERR_ASSERTION]: Missing siteUrl from office.com URL parameter
    at getRequiredParam (E:\FluidFramework\packages\drivers\fluidapp-odsp-urlResolver\dist\urlResolver.js:26:26)
    at FluidAppOdspUrlResolver.resolve (E:\FluidFramework\packages\drivers\fluidapp-odsp-urlResolver\dist\urlResolver.js:32:23)
    at Object.configurableUrlResolver (E:\FluidFramework\packages\loader\driver-utils\dist\multiUrlResolver.js:16:35)
    at async resolveUrl (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchInit.js:99:22)
    at async Object.fluidFetchInit (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchInit.js:103:25)
    at async fluidFetchOneFile (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetch.js:19:29)
generatedMessage: false
code: "ERR_ASSERTION"
actual: null
expected: true
operator: "=="

Also names do not match:
FluidFramework\packages\tools\**fetch-tool**\**fluid-fetch**

fluid-fetch should be renamed to fetch-tool

**Comment by jatgarg** [comment]
@heliocliu I am able to fetch ops without escaping the ! character in driveId. However I am hitting some other error.
Are you sure you got this: ERROR: AssertionError [ERR_ASSERTION]: Missing siteUrl from office.com URL parameter ?

**Comment by jatgarg** [comment]
As I talked with the helio, the error he was saying was a different one. So closing this issue for now.
