### ISSUE TITLE
Fetch tool fails to download snapshots

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#3541]
I've opened a bunch of issues with fluid-fetch failing to retrieve tokens, failing to get content using office.com links
But even if I can work-around all these issues, and it actually downloads ops for file on fluid preview, it fails to download snapshot with not much explanaiton:

ERROR: Error: Failed to load snapshot tree
    at fetchBlobsFromVersion (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:156:31)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fluidFetchSnapshot (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:209:31)
    at async fluidFetchOneFile (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetch.js:33:5)

We should
1. Expose better error message (sounds like we eat exception)
2, Fix the actual underlying problem.

**Comment by jatgarg** [comment]
https://github.com/microsoft/FluidFramework/pull/3633
