### ISSUE TITLE
Error when bundle with  SPFX

### ISSUE THREAD

**Issue by ilyhel** [microsoft/FluidFramework#3674]
## Describe the bug

Many TS1005 and TS1009...   Errors when  bundle spfx package in @fluidframework/aqueduct and other Dist folders in node_modules

### To Reproduce

 Create new spfx  Extension and  add install Fluid packages :
     "@fluidframework/aqueduct": "^0.26.0",
    "@fluidframework/get-tinylicious-container": "^0.26.0",
    "@fluidframework/map": "^0.26.0",

Run Gulp bundle

**Comment by tylerbutler** [comment]
@ilyhel Thank you for reporting this problem! Can you share a project that reproduces this or point us to how we can reproduce this?

**Comment by ilyhel** [comment]
Hi @tylerbutler 
I am just working for demo to Run time track SharePoint Online logged users  and display the count on behalf an spfx extention I try to adjust hosts samples https://github.com/microsoft/FluidFramework/tree/0076d7e0c23fffcf5f6df042a1f49a6838c1b111/examples/hosts
But always I get this kind of errors when runing **gulp bundle**
or TS1128: Declaration or statement expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(219,5): err
or TS1128: Declaration or statement expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(220,13): er
ror TS1005: ',' expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(220,74): er
ror TS1005: ',' expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(220,86): er
ror TS1109: Expression expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(220,87): er
ror TS1005: ';' expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(224,16): er
ror TS1005: ';' expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(228,18): er
ror TS1005: ';' expected.
[23:06:45] Error - [tsc] node_modules/@fluidframework/test-runtime-utils/node_mo
dules/@fluidframework/runtime-definitions/dist/dataStoreContext.d.ts(233,34): er
ror TS1005: ',' expected.
I am using such version : 
[23:06:46] Project spfxfluiddemo version:0.0.1
[23:06:46] Build tools version:3.12.1
[23:06:46] Node version:v10.13.0
[23:06:46] Total duration:25 s
[23:06:46] Task errors:60

**Comment by SamBroner** [comment]
@ilyhel, this seems to be a syntax error in a .d.t.s file. Possibly due to a mismatched version of TS between SPFx and Fluid. Could you share the version numbers of the SPFx project? We may need to look at the project itself.

**Comment by ilyhel** [comment]
Hi @SamBroner, I use @microsoft/generator-sharepoint@1.11.0.
I figured out the problem I am tring to upgrade the "**rush-stack-compiler**" from **3-3** to **3-7** and use  **typescript version: 3.7.5** but now I get now errors :( 
```
[05:31:46] Error - [tslint] { Error: Cannot find module 'tslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\csgo\Desktop\clients\spfxfluiddemo\node_modu
les\tslint-microsoft-contrib\noFunctionExpressionRule.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3) code: 'MODUL
E_NOT_FOUND' }
```

**Comment by ilyhel** [comment]
I think I broke the project structure!!!
