### ISSUE TITLE
Tinylicious Server : Cannot find module '@fluidframework/server-services-utils'

### ISSUE THREAD

**Issue by woeterman94** [microsoft/FluidFramework#3798]
(https://github.com/microsoft/FluidFramework/tree/main/server/tinylicious)
In an attempt to deploy Tinylicious Server, I've run:

```
npm i
npm run build
```

Next I have uploaded the **dist** folder to Azure
When running `node dist/index.js` I get the following error

```
 PATH="$PATH:/home/site/wwwroot" node /home/site/wwwroot/index.js
2020-10-01T10:07:58.988569748Z internal/modules/cjs/loader.js:638
2020-10-01T10:07:58.988590949Z     throw err;
2020-10-01T10:07:58.988595349Z     ^
2020-10-01T10:07:58.988598749Z
2020-10-01T10:07:58.988602049Z Error: Cannot find module '@fluidframework/server-services-utils'
2020-10-01T10:07:58.988605549Z     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
2020-10-01T10:07:58.988608849Z     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
2020-10-01T10:07:58.988612149Z     at Module.require (internal/modules/cjs/loader.js:692:17)
2020-10-01T10:07:58.988615549Z     at require (internal/modules/cjs/helpers.js:25:18)
2020-10-01T10:07:58.988618949Z     at Object.<anonymous> (/home/site/wwwroot/index.js:16:33)
2020-10-01T10:07:59.013365184Z     at Module._compile (internal/modules/cjs/loader.js:778:30)
2020-10-01T10:07:59.013375484Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2020-10-01T10:07:59.013378884Z     at Module.load (internal/modules/cjs/loader.js:653:32)
2020-10-01T10:07:59.013381784Z     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2020-10-01T10:07:59.013436785Z     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Is there something I'm doing wrong?

**Comment by tylerbutler** [comment]
@woeterman94 Can you share your project so we can take a look?

**Comment by woeterman94** [comment]
- I cloned : https://github.com/microsoft/FluidFramework/tree/main/server/tinylicious
- Did NPM install
- NPM run build
- In my dist folder I ran node index.js

That gave me the error.

**Comment by curtisman** [comment]
You need to upload the installed node modules from the `npm install` too (i.e. the `node_modules` directory)

**Comment by tylerbutler** [comment]
@woeterman94 Thanks for sharing the repro steps you followed. As @curtisman mentioned, you need to install dependencies on your server or upload the node_modules folder that contains all the dependencies.

Please let us know if we misunderstood.

**Comment by woeterman94** [comment]
Upload the entire node_modules is far from ideal :/
