### ISSUE TITLE
Container.load perf event can get reported twice

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#3936]
## Describe the bug
@wes-carlson reported seeing this behavior in #3779. That bug is about the symptom being wrong when we hit this case, now we should figure out why it's happening at all.

The code path is the static function [`Container.load`](https://github.com/microsoft/FluidFramework/blob/0ba4288eca79b6d23ee354e6af282097977d230b/packages/loader/container-loader/src/container.ts#L226-L254), see callstack below.

### To Reproduce
@wes-carlson - do you have a consistent repro? You mentioned that you've seen this happening when running tests. If so, please also attach logs so we can see the other perf events for this scenario (the start and the first end/cancel report)

### Expected behavior
Whatever is causing the perf event to report the first time should also short-circuit the rest of the logic in `Container.load` through the error path.

### Logs
```
(node:31699) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'eventName' of undefined
    at PerformanceEvent.reportEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:411:43)
    at PerformanceEvent.end (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:394:14)
    at container.load.finally.then (/home/wes/fluid/packages/loader/container-loader/dist/container.js:139:27)
```

### Code snippet
The code in that callstack is this:

```
        return PerformanceEvent.timedExecAsync(container.logger, { eventName: "Load" }, async (event) => {
            return new Promise<Container>((res, rej) => {
                const version = request.headers?.[LoaderHeader.version];
                const pause = request.headers?.[LoaderHeader.pause];

                const onClosed = (err?: ICriticalContainerError) => {
                    // Depending where error happens, we can be attempting to connect to web socket
                    // and continuously retrying (consider offline mode)
                    // Host has no container to close, so it's prudent to do it here
                    const error = err ?? CreateContainerError("Container closed without an error");
                    container.close(error);
                    rej(error);
                };
                container.on("closed", onClosed);

                container.load(version, pause === true)
                    .finally(() => {
                        container.removeListener("closed", onClosed);
                    })
                    .then(
                        (props) => {
                            event.end(props);
                            res(container);
                        },
                        (error) => {
                            const err = CreateContainerError(error);
                            onClosed(err);
                        },
                    );
            });
        });

```

**Comment by markfields** [comment]
In #3779 @vladsud said:

> In addition to fixing telemetry (not hitting undefined de-reference), let's look at Contanier.load() flow and how we can hit this issue.
>
> The error suggests that cancel() was called before end() in .then handler.
> This suggests that "close" was invoked, and then load() succeeded.
> The code (other that unhandled exception) works correctly. I'd say two things needs to happen:
> 1. We need to understand why closing container does not fail load() and if it should fail load.
> 2. Irrespective of that, Container.load (static version) likely need to account for that flow and not result in unhandled exception somehow.

**Comment by wes-carlson** [comment]
I was looking at this a little bit yesterday and Vlad's assessment looks to be correct. `onClosed` rejects the promise which causes `timedExecAsync()` to cancel the event, but `container.load.finally.then` still tries to end it.

You can repro this by just closing the container in container.load.finally right before the onClosed handler is removed (or in non-static `Container.load()` after the call to `resume()` since `resume()` does throw if the container is closed). Then if you run `npm run test:mocha:verbose` in tests/end-to-end you will see a bunch of stacks like above (now `PerformanceEventAfterStop` since #3898 was merged) mixed in with `ContainerClose` and `CreateSummarizerError` events:

```
  fluid:telemetry:Container ContainerClose {"loaderId":"74d14065-2df2-47a3-89a9-1882f43ff703","clientType":"noninteractive/summarizer","loaderVersion":"0.28.0","containerId":"1b754bb2-5c7a-4221-93cf-6a28149ccf12","sequenceNumber":0,"category":"error","error":"whatever","docId":"defaultDocumentId","containerAttachState":"Attached","containerLoaded":false}  Error
  fluid:telemetry:Container     at Function.getStack (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:72:21)
  fluid:telemetry:Container     at Function.prepareErrorObject (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:67:43)
  fluid:telemetry:Container     at ChildLogger.sendErrorEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:104:25)
  fluid:telemetry:Container     at Container.close (/home/wes/fluid/packages/loader/container-loader/dist/container.js:331:25)
  fluid:telemetry:Container     at Container.load (/home/wes/fluid/packages/loader/container-loader/dist/container.js:753:14) +0ms
  fluid:telemetry:Container PerformanceEventAfterStop {"loaderId":"74d14065-2df2-47a3-89a9-1882f43ff703","clientType":"noninteractive/summarizer","loaderVersion":"0.28.0","containerId":"1b754bb2-5c7a-4221-93cf-6a28149ccf12","perfEventName":"Load","eventNameSuffix":"end","category":"error","docId":"defaultDocumentId","containerAttachState":"Attached","containerLoaded":true}  Error
  fluid:telemetry:Container     at Function.getStack (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:72:21)
  fluid:telemetry:Container     at Function.prepareErrorObject (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:67:43)
  fluid:telemetry:Container     at ChildLogger.sendErrorEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:104:25)
  fluid:telemetry:Container     at PerformanceEvent.reportEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:417:25)
  fluid:telemetry:Container     at PerformanceEvent.end (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:395:14)
  fluid:telemetry:Container     at container.load.finally.then (/home/wes/fluid/packages/loader/container-loader/dist/container.js:190:27) +0ms
  fluid:telemetry:SummaryManager CreateSummarizerError {"loaderId":"74d14065-2df2-47a3-89a9-1882f43ff703","clientType":"interactive","loaderVersion":"0.28.0","containerId":"aa4c5fb6-b927-41e2-bd27-b0a36b90efd7","runtimeVersion":"0.28.0","attempt":2,"category":"error","error":"whatever","clientId":"847e34f9-8be5-4170-a2fe-523843ddb059","docId":"defaultDocumentId","containerAttachState":"Attached","containerLoaded":true}  Error
  fluid:telemetry:SummaryManager     at Function.getStack (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:72:21)
  fluid:telemetry:SummaryManager     at Function.prepareErrorObject (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:67:43)
  fluid:telemetry:SummaryManager     at ChildLogger.sendErrorEvent (/home/wes/fluid/packages/utils/telemetry-utils/dist/logger.js:104:25)
  fluid:telemetry:SummaryManager     at createSummarizer.then (/home/wes/fluid/packages/runtime/container-runtime/dist/summaryManager.js:266:25) +0ms
```
