### ISSUE TITLE
ChannelDisposeError: Safe Summary contains really old ops causing file to not load

### ISSUE THREAD

**Issue by micahgodbolt** [microsoft/FluidFramework#4248]
From IcM ticket #212298442

> so i took a peek here and it looks like something really odd is happening. when a component fails to summarize we do something called a safe summary, this is basically the previous summary + ops. there is a safe summary here, but it contains super old ops.

```
ChannelDisposeError {
  "loaderId":"cd9f12ae-0311-48fd-b973-aaa7bf6ab0d3",
  "clientType":"interactive",
  "loaderVersion":"0.27.12",
  "containerId":"38c74a0d-4eff-4502-87da-afe6e8f88066",
  "runtimeVersion":"0.27.12",
  "fluidDataStoreId":"b235d556-11de-4f94-bfd1-de38256a14e0",
  "category":"error",
  "error":"Unexpected attach channel OP,\n is in pendingAttach set: false,\n is local channel contexts: false",
  "docId":"U92%2FX%2BYiso3NuTc97Cu%2Bcfk6cMcAHLCz6kLDO5mofUQ%3D",
  "containerAttachState":"Attached"
  }  AssertionError: Unexpected attach channel OP, is in pendingAttach set: false, is local channel contexts: false 
  at I.process (https://officefluidprodprvversionedcdn.azureedge.net/container/hashed/officeContainer.ff3920fa68e3c0b49af4.js:438:5408) 
  at Z.bindRuntime (https://officefluidprodprvversionedcdn.azureedge.net/container/hashed/officeContainer.ff3920fa68e3c0b49af4.js:166:15169) 
  at Z.realizeCore (https://officefluidprodprvversionedcdn.azureedge.net/container/hashed/officeContainer.ff3920fa68e3c0b49af4.js:166:12514) +0ms
```

IcM: 212298442

**Comment by anthony-murphy** [comment]
might be related to #4150

**Comment by anthony-murphy** [comment]
closing an dup of #4296
