### ISSUE TITLE
Quick Start runs into error

### ISSUE THREAD

**Issue by svandenhoven** [microsoft/FluidFramework#5068]
I am new to FluidFramework and started the Quickstart, but ran into an issue immediatly:

Did the steps:

1. git clone https://github.com/microsoft/FluidHelloWorld.git
2. npm install
3. npm start

Looks like the error is here in "AsyncLocalStorage" that gave error ."AsyncLocalStorage is not a constructor"

[start:client] > webpack serve
[start:client]
[start:server] C:\Users\xyz\source\repos\FluidHelloWorld\node_modules\@fluidframework\server-services-utils\dist\asyncLocalStorage.js:16
[start:server] const asyncLocalStorage = new async_hooks_1.AsyncLocalStorage();
[start:server]                           ^
[start:server]
[start:server] TypeError: async_hooks_1.AsyncLocalStorage is not a constructor
[start:server]     at Object.<anonymous> (C:\Users\xyz\source\repos\FluidHelloWorld\node_modules\@fluidframework\server-services-utils\dist\asyncLocalStorage.js:16:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
[start:server]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[start:server]     at Module.load (internal/modules/cjs/loader.js:653:32)
[start:server]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[start:server]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
[start:server]     at require (internal/modules/cjs/helpers.js:25:18)
[start:server]     at Object.<anonymous> (C:\Users\xyz\source\repos\FluidHelloWorld\node_modules\@fluidframework\server-services-utils\dist\index.js:18:10)
[start:server]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[start:server] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[start:server] npm ERR! @fluid-example/hello-world@0.1.0 start:server: `tinylicious`
[start:server] npm ERR! Exit status 1
[start:server] npm ERR!
npm ERR! Failed at the @fluid-example/hello-world@0.1.0 start:server script.
[start:server] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[start:server]

**Comment by svandenhoven** [comment]
Wrong version of Node.js. :-(
