### ISSUE TITLE
Need isomorphic localStorage in OdspUtils

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#5108]
I've seen the stress test hit this error:

```
fluid:telemetry:Container ContainerClose {"loaderId":"24582743-e43d-423e-93fe-92eb1ba2992e","clientType":"interactive","loaderVersion":"0.35.0","containerId":"b49bd346-b1b4-4659-9cfd-65d549b5726e","sequenceNumber":0,"category":"error","error":"localStorage is not defined","message":"localStorage is not defined","errorType":"genericError","docId":"r3Ly8%2FFHIngtiUTw91wbOgSZUNbagx3ibib5PHRjQd8%3D","containerAttachState":"Attached","containerLoaded":true} tick=83467 ReferenceError: localStorage is not defined
  fluid:telemetry:Container     at connectWithAfd (D:\spo\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentService.js:266:17)
  fluid:telemetry:Container     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  fluid:telemetry:Container     at async D:\spo\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentService.js:178:36
  fluid:telemetry:Container     at async connectCore (D:\spo\FluidFramework\packages\loader\container-loader\dist\deltaManager.js:476:34) +0ms
```

Seems like the ODSP driver code is trying to use `localStorage` which isn't defined when running in a Node environment.

**Comment by curtisman** [comment]
Here: https://github.com/microsoft/FluidFramework/blob/69b8a0114abf793b35c61095b470b42020806d62/packages/drivers/odsp-driver/src/odspDocumentService.ts#L401
