### ISSUE TITLE
Fluid-fetch tool does not handle errors correctly

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5284]
It should retry on retriable errors. Can it use retriable storage adapter for all APIs?
Note that I believe we added "repeat to 3 times" when downloading ops, it likely have to stay there as is given that adapter only applies to storage requests.

Error calling getSnapshotTree bB5H9BAAHAAAA
ERROR: Error
    at EpochTrackerWithRedemption.checkForEpochError (E:\FluidFramework\packages\drivers\odsp-driver\dist\epochTracker.js:180:19)
    at EpochTrackerWithRedemption.fetchAndParseAsJSON (E:\FluidFramework\packages\drivers\odsp-driver\dist\epochTracker.js:86:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EpochTrackerWithRedemption.fetchAndParseAsJSON (E:\FluidFramework\packages\drivers\odsp-driver\dist\epochTracker.js:210:20)
    at async Function.timedExecAsync (E:\FluidFramework\packages\utils\telemetry-utils\dist\logger.js:308:25)
    at async E:\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentStorageManager.js:735:34
    at async OdspDocumentStorageService.readTree (E:\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentStorageManager.js:732:20)
    at async OdspDocumentStorageService.getSnapshotTree (E:\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentStorageManager.js:348:22)
    at async reportErrors (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:194:16)
    at async fetchBlobsFromVersion (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:186:18)
statusCode: 429
retryAfterSeconds: 1000
errorType: "throttlingError"
canRetry: true

**Comment by jatgarg** [comment]
Just commenting to keep it open from bot.
