### ISSUE TITLE
Fetch-tool failed with "Cannot read property 'push' of undefined"

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5309]
Got this error while running fluid-fetch tool on random file.
It worked (same bits) a moment before on another file, and I do not have any changes related to driver / tool:

Error calling getVersions
ERROR: Error: Fail to connect to ODSP server
Error Response:
TypeError: Cannot read property 'push' of undefined
    at Object.resolveWrapper (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSharePoint.js:38:31)
    at async Function.timedExecAsync (E:\Git\FluidFramework\packages\utils\telemetry-utils\dist\logger.js:308:25)
    at async E:\Git\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentStorageManager.js:472:34
    at async reportErrors (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:194:16)
    at async Object.fluidFetchSnapshot (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSnapshot.js:214:22)
    at async fluidFetchOneFile (E:\Git\FluidFramework\packages\tools\fetch-tool\dist\fluidFetch.js:32:5)

ResolveWrapper in fluidFetchSharePoint.ts should not eat error and rethrow as is!

Actual error:
ERROR: TypeError: Cannot read property 'push' of undefined
    at Object.get (E:\FluidFramework\packages\utils\tool-utils\dist\odspTokenManager.js:207:89)
    at async OdspTokenManager.getTokenFromCache (E:\FluidFramework\packages\utils\tool-utils\dist\odspTokenManager.js:70:27)
    at async OdspTokenManager.getTokens (E:\FluidFramework\packages\utils\tool-utils\dist\odspTokenManager.js:84:37)
    at async Object.resolveWrapper (E:\FluidFramework\packages\tools\fetch-tool\dist\fluidFetchSharePoint.js:20:24)

rc.tokens is undefined in odspTokensCache.get()

Using --forceTokenReauth fixed the problem.

**Comment by jatgarg** [comment]
https://github.com/microsoft/FluidFramework/pull/5289
