### ISSUE TITLE
Storage_uploadSummaryWithContext  gets 404 occasionally

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#5503]
Every once in a while I get this error in staging / production:
It would be great to get to the bottom of it:

bohemia.js:2 fluid:telemetry:DeltaManager Storage_uploadSummaryWithContext {"loaderId":"dfceae9c-da1e-4811-bf81-9801aeb1ba51","clientType":"noninteractive/summarizer","loaderVersion":"0.34.3","containerId":"baaf6257-04ff-40a9-80fc-8c4b95a836e9","retry":0,"duration":5686.549999983981,"category":"error","error":"Error 404","message":"Error 404","statusCode":404,"errorType":"fileNotFoundOrAccessDeniedError","canRetry":false,"online":"Online","response":"{\"error\":{\"code\":\"itemNotFound\",\"message\":\"Cannot locate node with id 'bB2IAAAAHAAAA'.\"}}","type":"cors","sprequestguid":"cc5eb39f-b025-0000-d53d-5f84e5a3b32e","serverEpoch":"cca15023-3d36-483f-917c-308eba9d5221","docId":"hA1Ln2O%2FfRXAUcMP0gmApfA%2BXrybKaw4DPZK9FHQKWs%3D","containerAttachState":"Attached","containerLoaded":true} tick=143440 Error: Error 404    at h (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:419553)    at a (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:431638)    at https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:434063    at async g (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:434347)    at async or.fetchAndParseAsJSON (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:127417)    at async https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:104134    at async Function.timedExecAsync (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:439996)    at async $t.writeSummaryTree (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:103243)    at async Function.timedExecAsync (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:439996)    at async Wt.uploadSummaryWithContext (https://officefluidprodprvversionedcdn.azureedge.net/7730809/app/bohemia.js:2:117161) +0ms

**Comment by vladsud** [comment]
union Office_Fluid_FluidRuntime_*
| where Data_eventName == "fluid:telemetry:OdspDriver:uploadSummaryWithContext_cancel"
| summarize count() by Data_error

Gives me these errors (filtered):

Error 404	   1479
Fetch error	1301
Error 503	1083
Coherency409	710
Error 404 (Not Found)	105

There are 87K of _start events, so 1% of summary uploads hit coherency failures and 2% hit 404.

**Comment by vladsud** [comment]
Using docId == "EqPBbAR51Sd9GuHAA19ywWEub7rlot3gRkgc62a6Zsg%3D" that hit a lot of these errors recently.
Data_containerId == "7802ed60-8e0c-45c6-9383-6a0673bc917d"

1. Successful summary at refSeq = 9884 with an ack. 26 seconds to hear an ack from server!
2. New summary, refSeq = 9887: fluid:telemetry:Summarizer:Running:SummaryNack	"Failed to summarize the document.". Note that upload took over 13 seconds (for a summary with only 3 ops, 2 of them are summaryOp & summaryAck), and it took 16 seconds to hear about nack after summaryOp.
3. New summary, refSeq = 9902:
   - fluid:telemetry:OdspDriver:LastSummaryProposedHandleMismatch
   - fluid:telemetry:Summarizer:Running:RefreshLatestSummaryGetSnapshot_end with hasVersion = true.
   - fluid:telemetry:Summarizer:Running:SummaryNack
"Proposed parent summary "bB5wmAAAHAAAA" does not match actual parent summary "bB58mAAAHAAAA"."
4. Followed by 404 on fluid:telemetry:OdspDriver:uploadSummary_cancel
5. next summary uploads fine, but gets nack "Proposed parent summary "bB5wmAAAHAAAA" does not match actual parent summary "bB58mAAAHAAAA"."
6. Next summary gets 404 on upload
7. And it keeps repeating back and forth between nack and 404 on upload many times until container is closed.

**Comment by vladsud** [comment]
docId = "8fcPkDUE3BZKHj9XRuqYhoh0lg4nLiiGkKYdsR%2BVc64%3D" has multiple sessions with 404, but they all have "Registry does not contain entry for the package" failures in between 404 and successful uploads.

docId = ""K5jnfJuskfVBZcsYbBO2ni0wJR%2BHYz89Fz98Z4qXMUA%3D" hits 409 (coherency failures) on summary upload, closed container, but then many minutes later - one more summary upload that gets 404.

Other sessions have no error events before 404 happens.
For example, containerId == "e01c806b-eb76-4c12-91ab-873d2630245f", sprequestguid = f045ce9f-0060-b000-f021-799dd7cc7b16
That said, it has 2 uploads without summaryOp or ack in between them and fluid:telemetry:OdspDriver:LastSummaryProposedHandleMismatch event suggesting that something went wrong on our side, but there are no events  other than fluid:telemetry:Summarizer:Running:SummarizeTimeout & fluid:telemetry:Summarizer:Running:MissingSummaryAckFoundByOps
There is also fluid:telemetry:Summarizer:HandleSummaryAckError 0x1a6 that follows.

**Comment by vladsud** [comment]
Stress test run confirmed that all nacks and majority of 404 are gone (that are no 404s in TAP5 run, and some small amount in higher runs).
Thus closing it.
