### ISSUE TITLE
Figure out OOM issues With Code Coverage and Re-enable

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#5954]
Figure out OOM issues With Code Coverage and Re-enable

_Originally posted by @anthony-murphy in https://github.com/microsoft/FluidFramework/pull/5945#r621404978_

**Comment by anthony-murphy** [comment]
FYI @curtisman @heliocliu @vladsud @DLehenbauer

**Comment by anthony-murphy** [comment]
```
2021-04-27T03:09:14.8120335Z ##[section]Starting: npm run ci:test:coverage
2021-04-27T03:09:14.8128896Z ==============================================================================
2021-04-27T03:09:14.8129441Z Task         : npm
2021-04-27T03:09:14.8130099Z Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
2021-04-27T03:09:14.8130752Z Version      : 1.182.0
2021-04-27T03:09:14.8131157Z Author       : Microsoft Corporation
2021-04-27T03:09:14.8131705Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
2021-04-27T03:09:14.8132332Z ==============================================================================
2021-04-27T03:09:15.4799718Z [command]/agent/_work/_tool/node/12.22.1/x64/bin/npm --version
2021-04-27T03:09:15.6070924Z 6.14.12
2021-04-27T03:09:16.4265055Z [command]/agent/_work/_tool/node/12.22.1/x64/bin/npm config list
2021-04-27T03:09:16.4265518Z ; cli configs
2021-04-27T03:09:16.4266098Z metrics-registry = "https://registry.npmjs.org/"
2021-04-27T03:09:16.4266555Z scope = ""
2021-04-27T03:09:16.4267094Z user-agent = "npm/6.14.12 node/v12.22.1 linux x64"
2021-04-27T03:09:16.4267317Z 
2021-04-27T03:09:16.4267621Z ; environment configs
2021-04-27T03:09:16.4268005Z userconfig = "/agent/_work/1/npm/23222.npmrc"
2021-04-27T03:09:16.4268210Z 
2021-04-27T03:09:16.4268584Z ; node bin location = /agent/_work/_tool/node/12.22.1/x64/bin/node
2021-04-27T03:09:16.4269007Z ; cwd = /agent/_work/1/s
2021-04-27T03:09:16.4269355Z ; HOME = /home/AzDevOps
2021-04-27T03:09:16.4269883Z ; "npm config ls -l" to show all defaults.
2021-04-27T03:09:16.4270083Z 
2021-04-27T03:09:16.4271811Z [command]/agent/_work/_tool/node/12.22.1/x64/bin/npm run ci:test:coverage
2021-04-27T03:10:25.9859352Z FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
2021-04-27T03:10:25.9860117Z  1: 0xa1a640 node::Abort() [node]
2021-04-27T03:10:25.9860318Z 
2021-04-27T03:10:25.9863307Z  2: 0xa1aa4c node::OnFatalError(char const*, char const*) [node]
2021-04-27T03:10:25.9864098Z > root@0.14.0 ci:test:coverage /agent/_work/1/s
2021-04-27T03:10:25.9864816Z > npm run test:coverage ; t1=$? ; npm run test:copyresults ; exit $t1
2021-04-27T03:10:25.9865654Z  3: 0xb9a68e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
2021-04-27T03:10:25.9866703Z  4: 0xb9aa09 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
2021-04-27T03:10:25.9867183Z 
2021-04-27T03:10:25.9867364Z 
2021-04-27T03:10:25.9867860Z > root@0.14.0 test:coverage /agent/_work/1/s
2021-04-27T03:10:25.9868484Z  5: 0xd57c85  [node]
2021-04-27T03:10:25.9869185Z  6: 0xd58316 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
2021-04-27T03:10:25.9870222Z  7: 0xd64bd5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
2021-04-27T03:10:25.9871412Z  8: 0xd65a85 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
2021-04-27T03:10:25.9872770Z  9: 0xd6853c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
2021-04-27T03:10:25.9874086Z 10: 0xd2ef5b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
2021-04-27T03:10:25.9875237Z 11: 0x107158e v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
2021-04-27T03:10:25.9876052Z 12: 0x140de99  [node]
2021-04-27T03:10:25.9876546Z Aborted (core dumped)
2021-04-27T03:10:25.9877011Z > nyc npm run test:report
2021-04-27T03:10:25.9877255Z 
2021-04-27T03:10:25.9877436Z 
2021-04-27T03:10:25.9878315Z <--- Last few GCs --->
2021-04-27T03:10:25.9878552Z 
2021-04-27T03:10:25.9879902Z [906:0x4d16e90]    65612 ms: Mark-sweep 2042.8 (2050.7) -> 2041.9 (2050.7) MB, 1223.1 / 0.0 ms  (average mu = 0.197, current mu = 0.158) allocation failure scavenge might not succeed
2021-04-27T03:10:25.9881990Z [906:0x4d16e90]    66897 ms: Mark-sweep 2043.1 (2050.9) -> 2042.1 (2050.9) MB, 1159.8 / 0.0 ms  (average mu = 0.156, current mu = 0.097) allocation failure scavenge might not succeed
2021-04-27T03:10:25.9882614Z 
2021-04-27T03:10:25.9882801Z 
2021-04-27T03:10:25.9883548Z <--- JS stacktrace --->
2021-04-27T03:10:25.9883813Z 
2021-04-27T03:10:25.9884360Z ==== JS stack trace =========================================
2021-04-27T03:10:25.9884704Z 
2021-04-27T03:10:25.9897323Z     0: ExitFrame [pc: 0x140de99]
2021-04-27T03:10:25.9898052Z Security context: 0x1876c06008d1 <JSObject>
2021-04-27T03:10:25.9899895Z     1: SourceMapConsumer_allGeneratedPositionsFor [0x2753aa8631e1] [/agent/_work/1/s/node_modules/@babel/core/node_modules/source-map/lib/source-map-consumer.js:~178] [pc=0x2089e275ef2f](this=0x0338b65cf7d9 <BasicSourceMapConsumer map = 0x11c9fd239739>,0x11a3ff4471b1 <Object map = 0x2c91444c4269>)
2021-04-27T03:10:25.9901276Z     2: /* anonymous */(aka /* anonymous */) [0x5480e7cc39] [/agent...
2021-04-27T03:10:25.9901660Z 
2021-04-27T03:10:25.9901827Z 
2021-04-27T03:10:25.9902345Z > root@0.14.0 test:copyresults /agent/_work/1/s
2021-04-27T03:10:25.9903344Z > copyfiles --exclude "**/node_modules/**" "**/nyc/**" nyc
2021-04-27T03:10:25.9903664Z 
2021-04-27T03:10:25.9939075Z npm ERR! code ELIFECYCLE
2021-04-27T03:10:25.9939731Z npm ERR! errno 134
2021-04-27T03:10:25.9940318Z npm ERR! root@0.14.0 test:coverage: `nyc npm run test:report`
2021-04-27T03:10:25.9940889Z npm ERR! Exit status 134
2021-04-27T03:10:25.9941231Z npm ERR! 
2021-04-27T03:10:25.9941633Z npm ERR! Failed at the root@0.14.0 test:coverage script.
2021-04-27T03:10:25.9942190Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-27T03:10:25.9942496Z 
2021-04-27T03:10:25.9942879Z npm ERR! A complete log of this run can be found in:
2021-04-27T03:10:25.9943857Z npm ERR!     /home/AzDevOps/.npm/_logs/2021-04-27T03_10_24_690Z-debug.log
2021-04-27T03:10:25.9944798Z npm ERR! code ELIFECYCLE
2021-04-27T03:10:25.9946135Z npm ERR! errno 134
2021-04-27T03:10:25.9946897Z npm ERR! root@0.14.0 ci:test:coverage: `npm run test:coverage ; t1=$? ; npm run test:copyresults ; exit $t1`
2021-04-27T03:10:25.9947579Z npm ERR! Exit status 134
2021-04-27T03:10:25.9947913Z npm ERR! 
2021-04-27T03:10:25.9948322Z npm ERR! Failed at the root@0.14.0 ci:test:coverage script.
2021-04-27T03:10:25.9948900Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-04-27T03:10:25.9949191Z 
2021-04-27T03:10:25.9949571Z npm ERR! A complete log of this run can be found in:
2021-04-27T03:10:25.9950353Z npm ERR!     /home/AzDevOps/.npm/_logs/2021-04-27T03_10_25_980Z-debug.log
2021-04-27T03:10:27.1573000Z Found npm debug log, make sure the path matches with the one in npm's output: /home/AzDevOps/.npm/_logs/2021-04-27T03_10_25_980Z-debug.log
2021-04-27T03:10:27.1573635Z 0 info it worked if it ends with ok
2021-04-27T03:10:27.1574021Z 1 verbose cli [
2021-04-27T03:10:27.1574608Z 1 verbose cli   '/agent/_work/_tool/node/12.22.1/x64/bin/node',
2021-04-27T03:10:27.1575264Z 1 verbose cli   '/agent/_work/_tool/node/12.22.1/x64/bin/npm',
2021-04-27T03:10:27.1575809Z 1 verbose cli   'run',
2021-04-27T03:10:27.1576498Z 1 verbose cli   'ci:test:coverage'
2021-04-27T03:10:27.1576875Z 1 verbose cli ]
2021-04-27T03:10:27.1577207Z 2 info using npm@6.14.12
2021-04-27T03:10:27.1577562Z 3 info using node@v12.22.1
2021-04-27T03:10:27.1578257Z 4 verbose run-script [ 'preci:test:coverage', 'ci:test:coverage', 'postci:test:coverage' ]
2021-04-27T03:10:27.1578893Z 5 info lifecycle root@0.14.0~preci:test:coverage: root@0.14.0
2021-04-27T03:10:27.1579404Z 6 info lifecycle root@0.14.0~ci:test:coverage: root@0.14.0
2021-04-27T03:10:27.1580132Z 7 verbose lifecycle root@0.14.0~ci:test:coverage: unsafe-perm in lifecycle true
2021-04-27T03:10:27.1581458Z 8 verbose lifecycle root@0.14.0~ci:test:coverage: PATH: /agent/_work/_tool/node/12.22.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/agent/_work/1/s/node_modules/.bin:/agent/_work/_tool/node/12.22.1/x64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
2021-04-27T03:10:27.1582682Z 9 verbose lifecycle root@0.14.0~ci:test:coverage: CWD: /agent/_work/1/s
2021-04-27T03:10:27.1583215Z 10 silly lifecycle root@0.14.0~ci:test:coverage: Args: [
2021-04-27T03:10:27.1583795Z 10 silly lifecycle   '-c',
2021-04-27T03:10:27.1584480Z 10 silly lifecycle   'npm run test:coverage ; t1=$? ; npm run test:copyresults ; exit $t1'
2021-04-27T03:10:27.1584963Z 10 silly lifecycle ]
2021-04-27T03:10:27.1585439Z 11 silly lifecycle root@0.14.0~ci:test:coverage: Returned: code: 134  signal: null
2021-04-27T03:10:27.1586055Z 12 info lifecycle root@0.14.0~ci:test:coverage: Failed to exec ci:test:coverage script
2021-04-27T03:10:27.1586750Z 13 verbose stack Error: root@0.14.0 ci:test:coverage: `npm run test:coverage ; t1=$? ; npm run test:copyresults ; exit $t1`
2021-04-27T03:10:27.1587325Z 13 verbose stack Exit status 134
2021-04-27T03:10:27.1588151Z 13 verbose stack     at EventEmitter.<anonymous> (/agent/_work/_tool/node/12.22.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
2021-04-27T03:10:27.1588834Z 13 verbose stack     at EventEmitter.emit (events.js:314:20)
2021-04-27T03:10:27.1589726Z 13 verbose stack     at ChildProcess.<anonymous> (/agent/_work/_tool/node/12.22.1/x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2021-04-27T03:10:27.1590386Z 13 verbose stack     at ChildProcess.emit (events.js:314:20)
2021-04-27T03:10:27.1590912Z 13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
2021-04-27T03:10:27.1591479Z 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
2021-04-27T03:10:27.1591967Z 14 verbose pkgid root@0.14.0
2021-04-27T03:10:27.1592329Z 15 verbose cwd /agent/_work/1/s
2021-04-27T03:10:27.1592852Z 16 verbose Linux 5.4.0-1039-azure
2021-04-27T03:10:27.1593553Z 17 verbose argv "/agent/_work/_tool/node/12.22.1/x64/bin/node" "/agent/_work/_tool/node/12.22.1/x64/bin/npm" "run" "ci:test:coverage"
2021-04-27T03:10:27.1594102Z 18 verbose node v12.22.1
2021-04-27T03:10:27.1594444Z 19 verbose npm  v6.14.12
2021-04-27T03:10:27.1594785Z 20 error code ELIFECYCLE
2021-04-27T03:10:27.1595121Z 21 error errno 134
2021-04-27T03:10:27.1595623Z 22 error root@0.14.0 ci:test:coverage: `npm run test:coverage ; t1=$? ; npm run test:copyresults ; exit $t1`
2021-04-27T03:10:27.1596148Z 22 error Exit status 134
2021-04-27T03:10:27.1596568Z 23 error Failed at the root@0.14.0 ci:test:coverage script.
2021-04-27T03:10:27.1597123Z 23 error This is probably not a problem with npm. There is likely additional logging output above.
2021-04-27T03:10:27.1597603Z 24 verbose exit [ 134, true ]
2021-04-27T03:10:27.1597781Z 
2021-04-27T03:10:27.1621030Z ##[error]Error: Npm failed with return code: 134
2021-04-27T03:10:27.1630784Z ##[section]Finishing: npm run ci:test:coverage
```

**Comment by DLehenbauer** [comment]
(Fixed by conversion to c8.)
