### ISSUE TITLE
SharedMatrix/UndoRedo: Error thrown in edge case using test implementation of UndoRedoStackManager

### ISSUE THREAD

**Issue by DLehenbauer** [microsoft/FluidFramework#6288]
## Describe the bug
While testing SharedMatrix with GC, @agarwal-navin encountered an error when an undo operation took the matrix back to its state of 0-rows and 0-cols without having first issued a '.closeCurrentOperation()'.

Probably low impact.  Also probably a trivial fix.

### To Reproduce
Navin saved his test repo [here](https://github.com/agarwal-navin/FluidFramework/blob/4d35463fb6834289af8807208ff44c179a577922/packages/test/test-end-to-end-tests/src/test/gcReferenceUpdatesInLocalSummary.spec.ts)

### Logs
Error: RangeOutOfBounds
      at PermutationVector.getValidOpRange (/fluid/fluidframework/packages/dds/merge-tree/dist/client.js:420:23)
      at PermutationVector.applyRemoveRangeOp (/fluid/fluidframework/packages/dds/merge-tree/dist/client.js:279:28)
      at PermutationVector.removeRangeLocal (/fluid/fluidframework/packages/dds/merge-tree/dist/client.js:158:18)
      at PermutationVector.remove (/fluid/fluidframework/packages/dds/matrix/dist/permutationvector.js:174:21)
      at SharedMatrix.removeCols (/fluid/fluidframework/packages/dds/matrix/dist/matrix.js:200:41)
      at /fluid/fluidframework/packages/dds/matrix/dist/undoprovider.js:107:25
      at Object.revert (/fluid/fluidframework/packages/dds/matrix/dist/undoprovider.js:70:25)
      at Function.revert (/fluid/fluidframework/packages/framework/undo-redo/dist/undoRedoStackManager.js:101:35)
      at UndoRedoStackManager.undoOperation (/fluid/fluidframework/packages/framework/undo-redo/dist/undoRedoStackManager.js:128:30)
      at Context.<anonymous> (/fluid/fluidframework/packages/test/test-end-to-end-tests/dist/test/gcReferenceUpdatesInLocalSummary.spec.js:66:52)
      at processImmediate (internal/timers.js:461:21)
      at process.callbackTrampoline (internal/async_hooks.js:131:14)

**Comment by DLehenbauer** [comment]
@agarwal-navin - Bug was legit.  Thanks for capturing the repo!

**Comment by agarwal-navin** [comment]
I think you closed it by mistake?

**Comment by DLehenbauer** [comment]
Already fixed.  :-)

PR #6341

**Comment by agarwal-navin** [comment]
Awesome :-)
