### ISSUE TITLE
getting genericError instead of fileNotFoundOrAccessDenied when hydrate Fluid link that doesn't exist

### ISSUE THREAD

**Issue by akrantz** [microsoft/FluidFramework#6620]
## Describe the bug

In Outlook Win32 email with a Fluid link to something that doesn't exist, we used to get back and error and show the message related to FileNotFoundOrAccessDenied. Now, we are getting a genericError with Storage Service disposed, leading to a Reload message which isn't right.

### To Reproduce
1. In OWA, create an email and insert a Fluid component.
2. Send an email to yourself.
3. Go to Sharepoint and delete the component.
4. In Outlook Win32, read the email that has the link to a non-existing Fluid document.

### Expected behavior
* The rejected promise from loadComponentInDiv() container should be fileNotFoundOrAccessDenied (not genericError).
* Should show error message banner for file not found.

### Logs

Failed to load resource: the server responded with a status of 404 () [****]
Failed to load resource: the server responded with a status of 403 () [****]
[0;95mfluid:telemetry:OdspDriver TreeLatest_SecondCall {"hasClaims":false,"hasTenantId":false,"category":"error","clientType":"interactive","loaderVersion":"0.39.1","containerId":"a77986e9-3bb3-4e5d-9078-40b94f02dbab","docId":"gb6C2Wjj%2F7QSkHzTSMK%2BMzaH3MLKr9m%2BRLwyLuJWVck%3D","containerAttachState":"Attached","containerLoaded":false,"driverVersion":"0.39.1","odc":false,"dmInitialSeqNumber":0,"dmLastKnownSeqNumber":0,"loaderId":"281dd675-ee52-4257-bbb9-15d703e63856"} tick=5914 [0;95m +0ms
Failed to load resource: the server responded with a status of 404 () [https://microsoft-my.sharepoint-df.com/_api/v2.1/drives/b!zQPnGLRDgku4lZr194EWSZluHe8Ix4dHptnO7USE2elmwqocGukbR4gSxd4zqBuS/items/01I2AH64L7G6TGGQ5QGVCJYLVCRLYZ5A7Z/opStream/joinSession?]
Failed to load resource: the server responded with a status of 403 () [https://microsoft-my.sharepoint-df.com/_api/v2.1/drives/b!zQPnGLRDgku4lZr194EWSZluHe8Ix4dHptnO7USE2elmwqocGukbR4gSxd4zqBuS/items/01I2AH64L7G6TGGQ5QGVCJYLVCRLYZ5A7Z/opStream/snapshots/trees/latest?ump=1]
[0;91mfluid:telemetry:Container ContainerClose {"sequenceNumber":0,"category":"error","error":"Storage service disposed!!","message":"Storage service disposed!!","__isFluidLoggingError__":1,"errorType":"genericError","clientType":"interactive","loaderVersion":"0.39.1","containerId":"a77986e9-3bb3-4e5d-9078-40b94f02dbab","docId":"gb6C2Wjj%2F7QSkHzTSMK%2BMzaH3MLKr9m%2BRLwyLuJWVck%3D","containerAttachState":"Attached","containerLoaded":false,"dmInitialSeqNumber":0,"dmLastKnownSeqNumber":0,"loaderId":"281dd675-ee52-4257-bbb9-15d703e63856"} tick=6177 Error: Storage service disposed!!
    at CreateContainerError (https://localhost:3000/static/js/vendors~main.chunk.js:34238:12)
    at RetriableDocumentStorageService.checkStorageDisposed (https://localhost:3000/static/js/vendors~main.chunk.js:27369:108)
    at https://localhost:3000/static/js/vendors~main.chunk.js:27346:209
    at runWithRetry (https://localhost:3000/static/js/vendors~main.chunk.js:27531:21)
    at async Container.getVersion (https://localhost:3000/static/js/vendors~main.chunk.js:24042:22)
    at async Container.fetchSnapshotTree (https://localhost:3000/static/js/vendors~main.chunk.js:24686:21)
    at async Container.load (https://localhost:3000/static/js/vendors~main.chunk.js:24106:9)[0;91m +0ms
Error during caching Container on the Loader
Error: Storage service disposed!!
Unable to load the Fluid container or component.Error: Storage service disposed!!
Hydrate failed: Error_FluidDriver_GenericError (3003).
Failed to load resource: the server responded with a status of 404 () [**REDACTED**]
Sharepoint REST response/result was empty when getting fluid file name
Error: Storage service disposed!!
    at CreateContainerError (https://localhost:3000/static/js/vendors~main.chunk.js:34238:12)
    at RetriableDocumentStorageService.checkStorageDisposed (https://localhost:3000/static/js/vendors~main.chunk.js:27369:108)
    at https://localhost:3000/static/js/vendors~main.chunk.js:27346:209
    at runWithRetry (https://localhost:3000/static/js/vendors~main.chunk.js:27531:21)
    at async Container.getVersion (https://localhost:3000/static/js/vendors~main.chunk.js:24042:22)
    at async Container.fetchSnapshotTree (https://localhost:3000/static/js/vendors~main.chunk.js:24686:21)
    at async Container.load (https://localhost:3000/static/js/vendors~main.chunk.js:24106:9)
AppError: Unable to load the Fluid container or component. genericError
    at onFluidLoadError (c:\dev\git\olk-win32-fluid\fluidhost\src\fluid\errors.ts:56:1)
    at async c:\dev\git\olk-win32-fluid\fluidhost\src\fluid\ComponentUXComposition.tsx:131:1

**Comment by jatgarg** [comment]
It was a regression caused in 0.39 driver version where we had code to handle the join session/trees latest race where trees latest needed to be executed first as it does the redeem. As I was seeing this driver version was using the class which does not handle that. However it seemed to be fixed from 0.39.4 version. Also consulted with the owner of the issue who is not seeing this anymore after upgrading. So closing this issue.
