### ISSUE TITLE
Unhandled exception when fetching snapshot times out

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#6996]
We are hitting this unhandled exception when fetch times out.
Any chance one of you can help me trace where we are lacking putting catch(() => {})?
@chensixx, I think you fixed one such case, this happens on recent bits in ODSP stress tests.

UnhandledPromiseRejection

Error
    at createOdspNetworkError (/app/packages/utils/odsp-doclib-utils/dist/odspErrorUtils.js:123:21)
    at Object.throwOdspNetworkError (/app/packages/utils/odsp-doclib-utils/dist/odspErrorUtils.js:161:26)
    at /app/packages/drivers/odsp-driver/dist/odspUtils.js:82:33
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.fetchAndParseAsJSONHelper (/app/packages/drivers/odsp-driver/dist/odspUtils.js:119:62)
    at async EpochTrackerWithRedemption.fetchAndParseAsJSON (/app/packages/drivers/odsp-driver/dist/epochTracker.js:109:30)
    at async EpochTrackerWithRedemption.fetchAndParseAsJSON (/app/packages/drivers/odsp-driver/dist/epochTracker.js:268:20)
    at async /app/packages/drivers/odsp-driver/dist/fetchSnapshot.js:141:30
    at async Function.timedExecAsync (/app/packages/utils/telemetry-utils/dist/logger.js:302:25)
    at async OdspDocumentStorageService.fetchSnapshotCore (/app/packages/drivers/odsp-driver/dist/odspDocumentStorageManager.js:419:34)

**Comment by anthony-murphy** [comment]
@chensixx is this bug ready to close now that the above pr is in?

**Comment by chensixx** [comment]
no, we did not find the exception, the unit test was to rule out some scenarios. Jatin said we should add telemetry when unhandled exceptions happen. I will follow up when he is back

**Comment by chensixx** [comment]
#7642 changed to awaiting both promises, and we do not see the error anymore in stress tests. Resolving now.
