### ISSUE TITLE
Exceptions thrown while processing sequence ops do not result in container closure.

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7800]
Putting it as October for now as this is one of the top error hits in 0.48
I.e. data is rather clean for FF, but we do see a bunch of host / component errors that manifest themselves through our telemetry, and some of that seems to be pointing to secondary bugs in FF.

When looking at overall error rate for 0.48, I see a bunch of errors that show up only as warning, and do not register anywhere else (including container closure). They look very suspicious. An example:

Office_Fluid_FluidRuntime_Error
| where Data_loaderVersion contains "0.48"
| where Data_error contains "sharedNode does not have attached modelNode"
| summarize count() by Data_containerId

Drilling into sample of container:

union Office_Fluid_FluidRuntime_Error
| where Data_containerId == "bfe17619-5780-4b9b-83bc-03ab8d93df8a" 
| summarize count() by Data_stack

We see that all stacks (even though they are truncated) look something like that:
> TypeError
    at https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/6109.d40c16a4d50a1f8bfb27.js:2:549209
    at ue.syncModel (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/6109.d40c16a4d50a1f8bfb27.js:2:928588)
    at ue.syncReceivedSequenceDeltaOp (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/6109.d40c16a4d50a1f8bfb27.js:2:548136)
    at o.<anonymous> (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/6109.d40c16a4d50a1f8bfb27.js:2:544595)
    at o.i.emit (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/ch5Container.383e6b15662d25eab082.js:2:125870)
    at o.emit (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/ch5Container.383e6b15662d25eab082.js:2:67020)
    at _.client.mergeTreeDeltaCallback.client.mergeTreeDeltaCallback (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/1835.b9d609bf5f61425a2b56.js:2:24738)
    at _.markRangeRemoved (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/6530.bcafb695fa1e2aef480f.js:2:72740)
    at y.applyRemoveRangeOp (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/6530.bcafb695fa1e2aef480f.js:2:12688)
    at y.applyRemoteOp (https://dev.ch5.fluidpreview.office.net/fluid/stg/ch5-container/hashed/6530.bcafb695fa1e2aef480f.js:2:18130),

Why an exception thrown while processing an op does not result in container closure? We are leaving application in inconsistent state!
While app / components should never throw exceptions to us (opened a bug about it to Scriptor), framework should have proper handling in here, which should be closing container.

We do catch exceptions and close container if ops are processed in normal flow (i.e. merge tree containing DDS is fully loaded).
The only place I see where it's not the case is loadCore() / loadCatchUpOps promise.

Exceptions are delivered to this.loadFinished(error).
That said, I do not see any other errors in telemetry, even though we should expect something:
```typescript
        this.loadedDeferred.promise.catch((error)=>{
            this.logger.sendErrorEvent({ eventName: "SequenceLoadFailed" }, error);
        });
```

Warnings are coming through ContainerRuntime.raiseContainerWarning, here are some users:
1. this.summaryManager.on("summarizerWarning", this.raiseContainerWarning);
2. SharedObject - through "error" event on itself

There are no other cases, I think it's # 2 as "error" event is raised whenever an exception is thrown by event handler.
I think usage of EventEmitterWithErrorHandling by SharedObject is justified (exceptions can be thrown on any event handler, it's hard to say how each of the paths is handled), but we should close container, not raise warning.

I believe that should be the main change - figure out how to make it happen.

**Comment by adrian726** [comment]
these are the bugs in Microsoft.
