### ISSUE TITLE
Lumberjack has not been setup yet erorrs

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#7870]
- running _npm run test_ in experimental\PropertyDDS\services\property-query\test\unit>
- running npm run start in examples\data-objects\shared-text

Produces 
  name: 'Error',
  message: 'Lumberjack has not been setup yet. It requires an engine list and an optional schema validator.',
  stack: 'Error: Lumberjack has not been setup yet. It requires an engine list and an optional schema validator.\n' +
    '    at Object.handleError (E:\\Git\\FluidFramework3\\node_modules\\@fluidframework\\server-services-telemetry\\dist\\resources.js:85:17)\n' +
    '    at Lumberjack.errorOnIncompleteSetup (E:\\Git\\FluidFramework3\\node_modules\\@fluidframework\\server-services-telemetry\\dist\\lumberjack.js:162:25)\n' +
    '    at Lumberjack.log (E:\\Git\\FluidFramework3\\node_modules\\@fluidframework\\server-services-telemetry\\dist\\lumberjack.js:96:14)\n' +
    '    at Function.info (E:\\Git\\FluidFramework3\\node_modules\\@fluidframework\\server-services-telemetry\\dist\\lumberjack.js:67:23)\n' +
    '    at Object.<anonymous> (E:\\Git\\FluidFramework3\\node_modules\\@fluidframework\\server-services-core\\dist\\debug.js:16:40)\n' +
    '    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n' +
    '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n' +
    '    at Module.load (internal/modules/cjs/loader.js:928:32)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n' +
    '    at Module.require (internal/modules/cjs/loader.js:952:19)'
}

Can we please fix this?

@znewton, can you please reassign as appropriate? Thanks!

**Comment by znewton** [comment]
#7675 fixed this I think
