### ISSUE TITLE
Socket error with circular json

### ISSUE THREAD

**Issue by GaryWilber** [microsoft/FluidFramework#8129]
I was running the service load test tool and these errors popped up at some point:

```
C:\Git\FluidFramework\packages\drivers\driver-base\dist\documentDeltaConnection.js:402
            message = `${message}: ${JSON.stringify(error)}`;
                                          ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property 'parser' -> object with constructor 'HTTPParser'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at OdspDocumentDeltaConnection.createErrorObject (C:\Git\FluidFramework\packages\drivers\driver-base\dist\documentDeltaConnection.js:402:43)
    at OdspDocumentDeltaConnection.createErrorObject (C:\Git\FluidFramework\packages\drivers\odsp-driver\dist\odspDocumentDeltaConnection.js:231:26)
    at Socket.<anonymous> (C:\Git\FluidFramework\packages\drivers\driver-base\dist\documentDeltaConnection.js:280:33)
    at Socket.Emitter.emit (C:\Git\FluidFramework\node_modules\component-emitter\index.js:145:20)
    at Socket.emit (C:\Git\FluidFramework\node_modules\socket.io-client\lib\socket.js:138:10)
    at Manager.emitAll (C:\Git\FluidFramework\node_modules\socket.io-client\lib\manager.js:82:27)
    at Socket.<anonymous> (C:\Git\FluidFramework\node_modules\socket.io-client\lib\manager.js:243:10)
    at Socket.Emitter.emit (C:\Git\FluidFramework\node_modules\component-emitter\index.js:145:20)
    at Socket.onError (C:\Git\FluidFramework\node_modules\engine.io-client\lib\socket.js:690:8)
   ```

Built off main as of 11/4. I ran it via a remote desktop and the VM was hitting 100% CPU so my connection was not stable. That potentially caused networking issues but I'm not certain.

**Comment by vladsud** [comment]
Based on line numbers, that's "connect_error" handler.
We detect correctly that is not IOdspSocketError, and take generic path.
There we take "TransportError" path and try to strigify websocket error, which results in this error.

**Comment by vladsud** [comment]
@GaryWilber, if you can hit it, any chance you can share the object (if you can attach debugger)? I have a guess it has token in it, I want to better understand privacy and circular reference aspects of it.

**Comment by GaryWilber** [comment]
`error.description.target` is a `WebSocket` object.

![image](https://user-images.githubusercontent.com/41303831/140572272-202b4d95-b1ce-43c3-977c-9955266886e9.png)
