### ISSUE TITLE
@fluid-experimental/property-inspector-table webpacking during build:compile and failing

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8455]
## Describe the bug
ideally packages wouldn't webpack during build compile, they should only webpack in build, or build full. Build compile should only compile, which provides the fastest way to compile everything.

additionally, i'm seeing the webpack step fail occasionally 
```
@fluid-experimental/property-inspector-table: error during command 'webpack --config webpack.prod.js --env.production'
@fluid-experimental/property-inspector-table: Hash: 10fc7c878f57b683890f2acb0d428fee9fe5deab
@fluid-experimental/property-inspector-table: Version: webpack 4.46.0
@fluid-experimental/property-inspector-table: Child
@fluid-experimental/property-inspector-table:     Hash: 10fc7c878f57b683890f
@fluid-experimental/property-inspector-table:     Time: 211775ms
@fluid-experimental/property-inspector-table:     Built at: 12/03/2021 4:26:34 PM
@fluid-experimental/property-inspector-table:                                                   Asset        Size                                        Chunks                   Chunk Names
@fluid-experimental/property-inspector-table:                                 ..\tsconfig.tsbuildinfo     449 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\CommonTypes.d.ts   729 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\CommonTypes.d.ts.map   549 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\CustomChip.d.ts   249 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\CustomChip.d.ts.map   320 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\DecoratedSelect.d.ts  1020 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                       ..\types\DecoratedSelect.d.ts.map   742 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\DeleteModal.d.ts    1.19 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\DeleteModal.d.ts.map   590 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                 ..\types\DeleteModalTextParameters.d.ts   674 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:             ..\types\DeleteModalTextParameters.d.ts.map   277 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                         ..\types\EditReferencePath.d.ts   370 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                     ..\types\EditReferencePath.d.ts.map   437 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                         ..\types\EditableValueCell.d.ts    5.97 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                     ..\types\EditableValueCell.d.ts.map   551 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\Empty.d.ts    1.12 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\Empty.d.ts.map   618 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\ErrorPopup.d.ts    1.38 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\ErrorPopup.d.ts.map   494 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\ErrorTooltip.d.ts   204 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\ErrorTooltip.d.ts.map   261 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\ExpiryModal.d.ts   499 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\ExpiryModal.d.ts.map   523 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\Field.d.ts   211 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\Field.d.ts.map   255 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                    ..\types\FloatingLabelTextField.d.ts    5.63 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                ..\types\FloatingLabelTextField.d.ts.map   420 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\InputValidator.d.ts   423 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\InputValidator.d.ts.map   213 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\InspectorDecorator.d.ts   162 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                    ..\types\InspectorDecorator.d.ts.map   190 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\InspectorModal.d.ts   451 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\InspectorModal.d.ts.map   400 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\InspectorTable.d.ts    3.07 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\InspectorTable.d.ts.map   548 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                   ..\types\InspectorTableDecorator.d.ts   289 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:               ..\types\InspectorTableDecorator.d.ts.map   212 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\InspectorTableFooter.d.ts   578 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                  ..\types\InspectorTableFooter.d.ts.map   461 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\InspectorTableHeader.d.ts   366 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                  ..\types\InspectorTableHeader.d.ts.map   308 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                       ..\types\InspectorTableTypes.d.ts    5.99 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                   ..\types\InspectorTableTypes.d.ts.map    3.88 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\ItemMenu.d.ts    1.55 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\ItemMenu.d.ts.map   967 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\LoadingButton.d.ts    5.48 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                         ..\types\LoadingButton.d.ts.map   398 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\ModalManager.d.ts     1.1 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\ModalManager.d.ts.map   776 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\ModalRoot.d.ts   255 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\ModalRoot.d.ts.map   210 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\NameCell.d.ts    5.57 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\NameCell.d.ts.map   510 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\NewDataForm.d.ts   761 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\NewDataForm.d.ts.map   504 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\NewDataRow.d.ts   722 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\NewDataRow.d.ts.map   351 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                       ..\types\NotificationsViewer.d.ts    21.2 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                   ..\types\NotificationsViewer.d.ts.map   748 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\OverflowableCell.d.ts   458 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\OverflowableCell.d.ts.map   341 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:              ..\types\PropertyDataCreationHandlers.d.ts   518 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:          ..\types\PropertyDataCreationHandlers.d.ts.map   378 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                     ..\types\PropertyViews\Boolean.d.ts   690 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                 ..\types\PropertyViews\Boolean.d.ts.map   584 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\PropertyViews\Enum.d.ts   695 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                    ..\types\PropertyViews\Enum.d.ts.map   617 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\PropertyViews\Number.d.ts   784 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                  ..\types\PropertyViews\Number.d.ts.map   674 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\PropertyViews\String.d.ts   663 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                  ..\types\PropertyViews\String.d.ts.map   570 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                   ..\types\SVGIcon.d.ts    1.12 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\SVGIcon.d.ts.map   460 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\SearchBox.d.ts   668 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\SearchBox.d.ts.map   665 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\ShareModal.d.ts    1.87 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\ShareModal.d.ts.map   901 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\Theme.d.ts   504 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\Theme.d.ts.map   304 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\TooltipedField.d.ts   471 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\TooltipedField.d.ts.map   411 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\TypeColumn.d.ts   395 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\TypeColumn.d.ts.map   320 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\TypeIcon.d.ts   275 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\TypeIcon.d.ts.map   244 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\constants.d.ts    1.48 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\constants.d.ts.map    1.07 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\icons.d.ts    1.17 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\icons.d.ts.map   372 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\index.d.ts   373 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\index.d.ts.map   251 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\typeUtils.d.ts    1.49 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\typeUtils.d.ts.map   904 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\utils.d.ts    7.11 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\utils.d.ts.map    2.57 KiB                                                [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\webpack.index.d.ts   480 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:                         ..\types\webpack.index.d.ts.map   335 bytes                                                [emitted]
@fluid-experimental/property-inspector-table:         @fluid-experimental/property-inspector-table.js    4.24 MiB  @fluid-experimental/property-inspector-table  [emitted]        @fluid-experimental/property-inspector-table
@fluid-experimental/property-inspector-table:     @fluid-experimental/property-inspector-table.js.map    3.97 MiB  @fluid-experimental/property-inspector-table  [emitted] [dev]  @fluid-experimental/property-inspector-table
@fluid-experimental/property-inspector-table:     Entrypoint @fluid-experimental/property-inspector-table = @fluid-experimental/property-inspector-table.js @fluid-experimental/property-inspector-table.js.map
@fluid-experimental/property-inspector-table:     [./assets/icons/SVGStoreIcons sync \.svg$/] ./assets/icons/SVGStoreIcons sync nonrecursive \.svg$/ 1.22 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./assets/icons/SVGStoreIcons/index.js] 792 bytes {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/EditReferencePath.tsx] 4.93 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/EditableValueCell.tsx] 3.75 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/Empty.tsx] 3.06 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/ExpiryModal.tsx] 15.4 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/InputValidator.ts] 1.5 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/InspectorTable.tsx] 42.9 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/InspectorTableFooter.tsx] 3.72 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/InspectorTableTypes.ts] 203 bytes {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/ModalManager.tsx] 4.02 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/ModalRoot.tsx] 1.53 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/PropertyDataCreationHandlers.ts] 3.7 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/icons.tsx] 6.06 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:     [./src/webpack.index.ts] 1.49 KiB {@fluid-experimental/property-inspector-table} [built]
@fluid-experimental/property-inspector-table:         + 726 hidden modules
@fluid-experimental/property-inspector-table:
@fluid-experimental/property-inspector-table:     ERROR in ./src/utils.tsx
@fluid-experimental/property-inspector-table:     Module build failed (from D:/code/fluid/node_modules/ts-loader/index.js):
@fluid-experimental/property-inspector-table:     Error: TypeScript emitted no output for D:\code\fluid\experimental\PropertyDDS\packages\property-inspector-table\src\utils.tsx.
@fluid-experimental/property-inspector-table:         at makeSourceMapAndFinish (D:\code\fluid\node_modules\ts-loader\dist\index.js:80:15)
@fluid-experimental/property-inspector-table:         at successLoader (D:\code\fluid\node_modules\ts-loader\dist\index.js:68:9)
@fluid-experimental/property-inspector-table:         at Object.loader (D:\code\fluid\node_modules\ts-loader\dist\index.js:22:12)
@fluid-experimental/property-inspector-table:      @ ./src/InspectorTable.tsx 143:14-32
@fluid-experimental/property-inspector-table:      @ ./src/webpack.index.ts
@fluid-experimental/property-inspector-table: Child
@fluid-experimental/property-inspector-table:     Hash: 2acb0d428fee9fe5deab
@fluid-experimental/property-inspector-table:     Time: 211682ms
@fluid-experimental/property-inspector-table:     Built at: 12/03/2021 4:26:34 PM
@fluid-experimental/property-inspector-table:                                                       Asset        Size  Chunks                          Chunk Names
@fluid-experimental/property-inspector-table:                                     ..\tsconfig.tsbuildinfo     449 KiB          [emitted]        [big]
@fluid-experimental/property-inspector-table:                                   ..\types\CommonTypes.d.ts   729 bytes          [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\CommonTypes.d.ts.map   549 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                    ..\types\CustomChip.d.ts   249 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\CustomChip.d.ts.map   320 bytes          [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\DecoratedSelect.d.ts  1020 bytes          [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\DecoratedSelect.d.ts.map   742 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                   ..\types\DeleteModal.d.ts    1.19 KiB          [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\DeleteModal.d.ts.map   590 bytes          [emitted]
@fluid-experimental/property-inspector-table:                     ..\types\DeleteModalTextParameters.d.ts   674 bytes          [emitted]
@fluid-experimental/property-inspector-table:                 ..\types\DeleteModalTextParameters.d.ts.map   277 bytes          [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\EditReferencePath.d.ts   370 bytes          [emitted]
@fluid-experimental/property-inspector-table:                         ..\types\EditReferencePath.d.ts.map   437 bytes          [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\EditableValueCell.d.ts    5.97 KiB          [emitted]
@fluid-experimental/property-inspector-table:                         ..\types\EditableValueCell.d.ts.map   551 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                         ..\types\Empty.d.ts    1.12 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\Empty.d.ts.map   618 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                    ..\types\ErrorPopup.d.ts    1.38 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\ErrorPopup.d.ts.map   494 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\ErrorTooltip.d.ts   204 bytes          [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\ErrorTooltip.d.ts.map   261 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                   ..\types\ExpiryModal.d.ts   499 bytes          [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\ExpiryModal.d.ts.map   523 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                         ..\types\Field.d.ts   211 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\Field.d.ts.map   255 bytes          [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\FloatingLabelTextField.d.ts    5.63 KiB          [emitted]
@fluid-experimental/property-inspector-table:                    ..\types\FloatingLabelTextField.d.ts.map   420 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\InputValidator.d.ts   423 bytes          [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\InputValidator.d.ts.map   213 bytes          [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\InspectorDecorator.d.ts   162 bytes          [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\InspectorDecorator.d.ts.map   190 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\InspectorModal.d.ts   451 bytes          [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\InspectorModal.d.ts.map   400 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\InspectorTable.d.ts    3.07 KiB          [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\InspectorTable.d.ts.map   548 bytes          [emitted]
@fluid-experimental/property-inspector-table:                       ..\types\InspectorTableDecorator.d.ts   289 bytes          [emitted]
@fluid-experimental/property-inspector-table:                   ..\types\InspectorTableDecorator.d.ts.map   212 bytes          [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\InspectorTableFooter.d.ts   578 bytes          [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\InspectorTableFooter.d.ts.map   461 bytes          [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\InspectorTableHeader.d.ts   366 bytes          [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\InspectorTableHeader.d.ts.map   308 bytes          [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\InspectorTableTypes.d.ts    5.99 KiB          [emitted]
@fluid-experimental/property-inspector-table:                       ..\types\InspectorTableTypes.d.ts.map    3.88 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                      ..\types\ItemMenu.d.ts    1.55 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\ItemMenu.d.ts.map   967 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\LoadingButton.d.ts    5.48 KiB          [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\LoadingButton.d.ts.map   398 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\ModalManager.d.ts     1.1 KiB          [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\ModalManager.d.ts.map   776 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\ModalRoot.d.ts   255 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\ModalRoot.d.ts.map   210 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                      ..\types\NameCell.d.ts    5.57 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\NameCell.d.ts.map   510 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                   ..\types\NewDataForm.d.ts   761 bytes          [emitted]
@fluid-experimental/property-inspector-table:                               ..\types\NewDataForm.d.ts.map   504 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                    ..\types\NewDataRow.d.ts   722 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\NewDataRow.d.ts.map   351 bytes          [emitted]
@fluid-experimental/property-inspector-table:                           ..\types\NotificationsViewer.d.ts    21.2 KiB          [emitted]
@fluid-experimental/property-inspector-table:                       ..\types\NotificationsViewer.d.ts.map   748 bytes          [emitted]
@fluid-experimental/property-inspector-table:                              ..\types\OverflowableCell.d.ts   458 bytes          [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\OverflowableCell.d.ts.map   341 bytes          [emitted]
@fluid-experimental/property-inspector-table:                  ..\types\PropertyDataCreationHandlers.d.ts   518 bytes          [emitted]
@fluid-experimental/property-inspector-table:              ..\types\PropertyDataCreationHandlers.d.ts.map   378 bytes          [emitted]
@fluid-experimental/property-inspector-table:                         ..\types\PropertyViews\Boolean.d.ts   690 bytes          [emitted]
@fluid-experimental/property-inspector-table:                     ..\types\PropertyViews\Boolean.d.ts.map   584 bytes          [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\PropertyViews\Enum.d.ts   695 bytes          [emitted]
@fluid-experimental/property-inspector-table:                        ..\types\PropertyViews\Enum.d.ts.map   617 bytes          [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\PropertyViews\Number.d.ts   784 bytes          [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\PropertyViews\Number.d.ts.map   674 bytes          [emitted]
@fluid-experimental/property-inspector-table:                          ..\types\PropertyViews\String.d.ts   663 bytes          [emitted]
@fluid-experimental/property-inspector-table:                      ..\types\PropertyViews\String.d.ts.map   570 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                       ..\types\SVGIcon.d.ts    1.12 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                   ..\types\SVGIcon.d.ts.map   460 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\SearchBox.d.ts   668 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\SearchBox.d.ts.map   665 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                    ..\types\ShareModal.d.ts    1.87 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\ShareModal.d.ts.map   901 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                         ..\types\Theme.d.ts   504 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\Theme.d.ts.map   304 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\TooltipedField.d.ts   471 bytes          [emitted]
@fluid-experimental/property-inspector-table:                            ..\types\TooltipedField.d.ts.map   411 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                    ..\types\TypeColumn.d.ts   395 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                ..\types\TypeColumn.d.ts.map   320 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                      ..\types\TypeIcon.d.ts   275 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                  ..\types\TypeIcon.d.ts.map   244 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\constants.d.ts    1.48 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\constants.d.ts.map    1.07 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                         ..\types\icons.d.ts    1.17 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\icons.d.ts.map   372 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                         ..\types\index.d.ts   373 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\index.d.ts.map   251 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\typeUtils.d.ts    1.49 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\typeUtils.d.ts.map   904 bytes          [emitted]
@fluid-experimental/property-inspector-table:                                         ..\types\utils.d.ts    7.11 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                     ..\types\utils.d.ts.map    2.57 KiB          [emitted]
@fluid-experimental/property-inspector-table:                                 ..\types\webpack.index.d.ts   480 bytes          [emitted]
@fluid-experimental/property-inspector-table:                             ..\types\webpack.index.d.ts.map   335 bytes          [emitted]
@fluid-experimental/property-inspector-table:         @fluid-experimental/property-inspector-table.min.js     958 KiB       0  [emitted]        [big]  @fluid-experimental/property-inspector-table.min
@fluid-experimental/property-inspector-table:     @fluid-experimental/property-inspector-table.min.js.map    3.54 MiB       0  [emitted] [dev]         @fluid-experimental/property-inspector-table.min
@fluid-experimental/property-inspector-table:     Entrypoint @fluid-experimental/property-inspector-table.min [big] = @fluid-experimental/property-inspector-table.min.js @fluid-experimental/property-inspector-table.min.js.map
@fluid-experimental/property-inspector-table:       [0] external "react" 42 bytes {0} [built]
@fluid-experimental/property-inspector-table:      [24] D:/code/fluid/node_modules/@material-ui/core/esm/styles/index.js + 6 modules 9.15 KiB {0} [built]
@fluid-experimental/property-inspector-table:           |    7 modules
@fluid-experimental/property-inspector-table:      [31] ./src/constants.ts 2.13 KiB {0} [built]
@fluid-experimental/property-inspector-table:      [39] ./src/SVGIcon.tsx 3.74 KiB {0} [built]
@fluid-experimental/property-inspector-table:      [98] ./src/ModalManager.tsx 4.02 KiB {0} [built]
@fluid-experimental/property-inspector-table:      [99] external "@fluid-experimental/property-properties" 42 bytes {0} [built]
@fluid-experimental/property-inspector-table:     [101] ./src/utils.tsx 33.9 KiB {0} [built]
@fluid-experimental/property-inspector-table:     [132] external "@fluid-experimental/property-proxy" 42 bytes {0} [built]
@fluid-experimental/property-inspector-table:     [188] ./src/icons.tsx 6.06 KiB {0} [built]
@fluid-experimental/property-inspector-table:     [321] ./src/webpack.index.ts 1.49 KiB {0} [built]
@fluid-experimental/property-inspector-table:     [322] ./assets/icons/SVGStoreIcons/index.js 792 bytes {0} [built]
@fluid-experimental/property-inspector-table:     [376] ./src/InspectorTable.tsx 42.9 KiB {0} [built]
@fluid-experimental/property-inspector-table:     [497] ./src/InspectorTableTypes.ts 203 bytes {0} [built]
@fluid-experimental/property-inspector-table:     [498] ./src/PropertyDataCreationHandlers.ts 3.7 KiB {0} [built]
@fluid-experimental/property-inspector-table:     [500] ./src/ModalRoot.tsx 1.53 KiB {0} [built]
@fluid-experimental/property-inspector-table:         + 529 hidden modules
@fluid-experimental/property-inspector-table:
@fluid-experimental/property-inspector-table:     WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
@fluid-experimental/property-inspector-table:     This can impact web performance.
@fluid-experimental/property-inspector-table:     Assets:
@fluid-experimental/property-inspector-table:       @fluid-experimental/property-inspector-table.min.js (958 KiB)
@fluid-experimental/property-inspector-table:       ..\tsconfig.tsbuildinfo (449 KiB)
@fluid-experimental/property-inspector-table:
@fluid-experimental/property-inspector-table:     WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
@fluid-experimental/property-inspector-table:     Entrypoints:
@fluid-experimental/property-inspector-table:       @fluid-experimental/property-inspector-table.min (958 KiB)
@fluid-experimental/property-inspector-table:           @fluid-experimental/property-inspector-table.min.js
@fluid-experimental/property-inspector-table:
@fluid-experimental/property-inspector-table:
@fluid-experimental/property-inspector-table:     WARNING in webpack performance recommendations:
@fluid-experimental/property-inspector-table:     You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
@fluid-experimental/property-inspector-table:     For more info visit https://webpack.js.org/guides/code-splitting/
[120/168] x @fluid-experimental/property-inspector-table: webpack --config webpack.prod.js --env.production - 217.134s
Build failed
```

**Comment by anthony-murphy** [comment]
@DLehenbauer any idea who should look at this?
