### ISSUE TITLE
Stress: writeBlob: `Runtime is closed` and `runtime disposed while blobAttach op in flight`

### ISSUE THREAD

**Issue by anthony-murphy** [microsoft/FluidFramework#8665]
Seeing blob related unhandled exceptions in the stress runs:
```
UnhandledPromiseRejection	Runtime is closed

Error
    at ContainerRuntime.verifyNotClosed (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-runtime/dist/containerRuntime.js:1564:19)
    at ContainerRuntime.submit (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-runtime/dist/containerRuntime.js:1482:14)
    at BlobManager.attachBlobCallback (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-runtime/dist/containerRuntime.js:466:136)
    at BlobManager.createBlob (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-runtime/dist/blobManager.js:92:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LoadTestDataStoreModel.writeBlob (/mnt/vss/_work/1/test/node_modules/@fluid-internal/test-service-load/dist/loadTestDataStore.js:229:28)
```
```
UnhandledPromiseRejection	runtime disposed while blobAttach op in flight
Error
    at ContainerRuntime.<anonymous> (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-runtime/dist/blobManager.js:55:32)
    at Object.onceWrapper (events.js:519:28)
    at ContainerRuntime.emit (events.js:400:28)
    at ContainerRuntime.dispose (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-runtime/dist/containerRuntime.js:745:14)
    at ContainerContext.dispose (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-loader/dist/containerContext.js:105:22)
    at Container.close (/mnt/vss/_work/1/test/node_modules/@fluidframework/container-loader/dist/container.js:476:78)
    at Timeout._onTimeout (/mnt/vss/_work/1/test/node_modules/@fluid-internal/test-service-load/dist/runner.js:278:39)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

we could probably fix these in the tests itself, but i'm wondering if they point to more fundamental problems with blob attach process. I don't actually understand why we need to wait for the blob op to round trip before we return the handle, in other similar cases, like dds and datastores we immediately return the handle. This is more inline with our optimistic eventual consistency model, and seems safe, and all subsequent ops would depend on that op, so the attach op must necessarily round trip before any other ops that reference its handle round trip.

FYI @DLehenbauer @vladsud @wes-carlson

**Comment by vladsud** [comment]
I believe we do want to move to a design where (from developer / FF user POV) blob addition is fully synchronous operation, similar to any other model (DDS) change. We have talked about it with Wes and I think it's design we are going with, which requires substantial changes in pending state manager and op resubmission logic.

It will not change lower-level behavior that you observe here and that likely needs to be addressed.
The reason we send op and wait for it is because we need to ensure that blob is "referenced" properly in a file and not GC'd by storage. We are trying to resolve a race condition with GC where blob is uploaded, but there are no other references to it in a file (let's say client taht uploaded it crashes), so we want GC to collect it. So, op sending and checking time of ack of that op is a mechanism that client can use to determine that blob is referenced by file and its lifetime management is shifted to runtime (from storage) - runtime now needs to start referencing it in future snapshots or it will be GC'd by storage.
If op is not acked in reasonable amount of time, client should assume it is collected (or could be collected) and needs to restart upload process (I do not remember if all of that is fully implemented, or Wes has work items to follow up).

This complicated mechanism is needed only because op stream is the only mechanism that gives order to events. All other mechanisms (like blob upload) need somehow to be "anchored" in op stream to reason about causality of events.

Maybe there are simpler mechanism to achieve same things, it has been a while since I thought about this process, so describing what I remember from earlier discussions with Wes, ODSP. If you see ways to simplify it - please share!

**Comment by vladsud** [comment]
To answer the key question - yes, we should not crash here - if container is closed, blob upload should silently fail (or silently succeed - I think we allow to change DDSs after container is closed, these changes do nothing, we should be consistent RE what we allow or not in this state, I think we are inconsistent, so maybe that's separate area to look at open some issues).

**Comment by anthony-murphy** [comment]
sounds good. in these cases the errors are not causing the container to close. they are actually the result of a container close which then lead to unhandled rejections. if those rejections are expected, then the right fix in probably in the test code

**Comment by vladsud** [comment]
I do not know if they are expected - see my last comment - I'm not sure how we want to deal with ability to mutate container state (across all APIs) after container closure - allow or throw. This particular stack is a bit unique (at the moment), as operation started likely before container was closed.

I'd love Wes to poke around and propose consistency model RE how we deal with issues like that in general, not just for this API.
For example, I believe
- DDSs allow mutation after closure
- Quorum (QuorumProxy specifically) does not allow even reads after closure (this seems too strong / unacceptable, user does not care about our structure / proxies).
- Container runtime does not allow sending signals (that's fine - we do not allow that in disconnected state, it's more general case)
- UploadBlob() fails (verifyNotClosed() check at the top, plus failure to send ops).
- I believe request() in flight (that needs to load data store) while container is closed will complete successfully - should it be allowed to complete, or should it fail?

Having consistency in this space (and opening issues to get there) would be great.
