### ISSUE TITLE
fetch-tool fails with "Cannot read property 'contents' of undefined"

### ISSUE THREAD

**Issue by vladsud** [microsoft/FluidFramework#8677]
Any chance you can help me take a look where it fails?

E:\Git\FluidFramework3\packages\tools\fetch-tool>node bin\fluid-fetch "https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!fj-qf9E4cEqEN2yG19SC8FA56ZHdGg5Puse1fuvRM9dWf8H6jmHESKEW0E6-yeH1&item=01L3MDHA3N7VZV7X2JY5G2NOFVOR2V3JJ2&file=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fjegour_microsoft_com&siteUrl=https:%2F%2Fmicrosoft-my.sharepoint-df.com%2Fpersonal%2Fjegour_microsoft_com" --stat

ERROR: TypeError: Cannot read property 'contents' of undefined
    at processOp (E:\Git\FluidFramework3\packages\tools\fetch-tool\dist\fluidAnalyzeMessages.js:452:61)
    at DataStructureAnalyzer.processOp (E:\Git\FluidFramework3\packages\tools\fetch-tool\dist\fluidAnalyzeMessages.js:186:13)
    at Object.printMessageStats (E:\Git\FluidFramework3\packages\tools\fetch-tool\dist\fluidAnalyzeMessages.js:389:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async fluidFetchOneFile (E:\Git\FluidFramework3\packages\tools\fetch-tool\dist\fluidFetch.js:33:5)

This is not FFX file, so can't be opened with Office.com, and not sure what version of Fluid was used to create it, but it was created pretty recently

**Comment by vladsud** [comment]
Also getting this error:

            assert(sequencedMessages[0].sequenceNumber === curr,
                0x1bb /* "Unexpected sequence number on first of messages to save" */);

When doing --saveDir

**Comment by anthony-murphy** [comment]
seeing similar error, 0x1bb went away after retry for me

**Comment by jatgarg** [comment]
Will take a look probably today.

**Comment by jatgarg** [comment]
@vladsud Can you please provide access to the document if possible so that I can debug as it seems to be working for me.

**Comment by jatgarg** [comment]
Seems like this is caused by the ChunkedOp. Seems like we don't have the ability to process the chunked op in fetch tool.
