### ISSUE TITLE
Reenable eslint rule  @typescript-eslint/unbound-method

### ISSUE THREAD

**Issue by markfields** [microsoft/FluidFramework#9082]
> @tylerbutler - This rule is pretty important if I understand it correctly, why did you disable it?

_Originally posted by @markfields in https://github.com/microsoft/FluidFramework/pull/8547#r803187283_

More info on the rule is here:  https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/unbound-method.md

Things will break badly if we start breaking it, as far as I can tell.

**Comment by tylerbutler** [comment]
According to the comment in the minimal config: "This rule has false positives in many of our test projects."

**Comment by tylerbutler** [comment]
The rule is only completely disabled in [the eslint7 config](https://github.com/microsoft/FluidFramework/blob/main/common/build/eslint-config-fluid/eslint7.js#L178), which is no longer used by any package in the repo since the upgrade to eslint 8.

The default config is now "minimal," which does disable the rule, but [only for test files.](https://github.com/microsoft/FluidFramework/blob/0271ff4cbb3f784f12a94eb2c00a93ccccfaf5ed/common/build/eslint-config-fluid/minimal.js#L117-L121), where there are lots of false positives.

**Comment by markfields** [comment]
Hmmm that's interesting.  As-is I can write a violation of the rule but not see an error.  On the other hand, when I added it directly to the package's eslint.js it did get caught.

**Comment by markfields** [comment]
I see it's disabled for test files, but... where is it _enabled_ to begin with? Are we missing something in the `extends` list?

**Comment by markfields** [comment]
> [the eslint7 config](https://github.com/microsoft/FluidFramework/blob/main/common/build/eslint-config-fluid/eslint7.js#L178), which is no longer used by any package in the repo

Can we delete it from main?

**Comment by markfields** [comment]
@ChumpChief - Assigning this to you since you're looking into restoring this and bunch of other rules to the common config.

**Comment by tylerbutler** [comment]
@ChumpChief @markfields I was reminded of why this got disabled originally... In a lot of projects, the rule throws an exception:

```
TypeError: Cannot read property '0' of undefined
Occurred while linting /workspaces/FluidFramework/common/lib/container-definitions/src/browserPackage.ts:58
Rule: "@typescript-eslint/unbound-method"
    at checkMethod (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:220:47)
    at checkMethodAndReport (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:155:53)
    at MemberExpression (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js:177:17)
    at ruleErrorHandler (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/eslint/lib/linter/linter.js:1079:28)
    at /workspaces/FluidFramework/common/lib/container-definitions/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/workspaces/FluidFramework/common/lib/container-definitions/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

I tried upgrading @typescript-eslint/eslint-plugin but it still repros. I'll start looking through their open issues...

**Comment by markfields** [comment]
That is a real bummer

**Comment by ChumpChief** [comment]
This just bit me today, I'm gonna prioritize it 😆

**Comment by markfields** [comment]
Thank you @ChumpChief !  What about the error Tyler mentioned above?

**Comment by ChumpChief** [comment]
I didn't hit it personally, so not sure exactly.
