### ISSUE TITLE
Local server logs Lumberjack error on page load and in test runs

### ISSUE THREAD

**Issue by ChumpChief** [microsoft/FluidFramework#9370]
Repros when running our examples in local mode, and for the examples' tests -- e.g. see the test stage of this pipeline run:
https://dev.azure.com/fluidframework/public/_build/results?buildId=55930&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=5cfe65a4-d7cb-5934-e953-1c67617821f4

```console
@fluid-example/webflow: {
@fluid-example/webflow:   name: 'Error',
@fluid-example/webflow:   message: 'Lumberjack has not been setup yet. It requires an engine list and an optional schema validator.',
@fluid-example/webflow:   stack: 'Error: Lumberjack has not been setup yet. It requires an engine list and an optional schema validator.\n' +
@fluid-example/webflow:     '    at Object.handleError (/mnt/vss/_work/1/s/node_modules/@fluidframework/server-services-core/node_modules/@fluidframework/server-services-telemetry/dist/resources.js:90:17)\n' +
@fluid-example/webflow:     '    at Lumberjack.errorOnIncompleteSetup (/mnt/vss/_work/1/s/node_modules/@fluidframework/server-services-core/node_modules/@fluidframework/server-services-telemetry/dist/lumberjack.js:162:25)\n' +
@fluid-example/webflow:     '    at Lumberjack.log (/mnt/vss/_work/1/s/node_modules/@fluidframework/server-services-core/node_modules/@fluidframework/server-services-telemetry/dist/lumberjack.js:96:14)\n' +
@fluid-example/webflow:     '    at Function.info (/mnt/vss/_work/1/s/node_modules/@fluidframework/server-services-core/node_modules/@fluidframework/server-services-telemetry/dist/lumberjack.js:67:23)\n' +
@fluid-example/webflow:     '    at MongoManager.connect (/mnt/vss/_work/1/s/node_modules/@fluidframework/server-services-core/dist/mongo.js:70:48)\n' +
@fluid-example/webflow:     '    at new MongoManager (/mnt/vss/_work/1/s/node_modules/@fluidframework/server-services-core/dist/mongo.js:18:31)\n' +
@fluid-example/webflow:     '    at Function.create (/mnt/vss/_work/1/s/node_modules/@fluidframework/server-local-server/dist/localDeltaConnectionServer.js:41:30)\n' +
@fluid-example/webflow:     '    at new LocalServerTestDriver (/mnt/vss/_work/1/s/packages/test/test-drivers/dist/localServerTestDriver.js:11:55)\n' +
@fluid-example/webflow:     '    at Object.createFluidTestDriver (/mnt/vss/_work/1/s/packages/test/test-drivers/dist/factory.js:67:20)\n' +
@fluid-example/webflow:     '    at createVersionedFluidTestDriver (/mnt/vss/_work/1/s/packages/test/test-version-utils/dist/compatUtils.js:54:27)\n' +
@fluid-example/webflow:     '    at Object.getVersionedTestObjectProvider (/mnt/vss/_work/1/s/packages/test/test-version-utils/dist/compatUtils.js:60:26)\n' +
@fluid-example/webflow:     '    at Context.<anonymous> (/mnt/vss/_work/1/s/packages/test/test-version-utils/dist/describeCompat.js:26:52)\n' +
@fluid-example/webflow:     '    at callFn (/mnt/vss/_work/1/s/node_modules/mocha/lib/runnable.js:366:21)\n' +
@fluid-example/webflow:     '    at Hook.Runnable.run (/mnt/vss/_work/1/s/node_modules/mocha/lib/runnable.js:354:5)\n' +
@fluid-example/webflow:     '    at next (/mnt/vss/_work/1/s/node_modules/mocha/lib/runner.js:510:10)\n' +
@fluid-example/webflow:     '    at Immediate._onImmediate (/mnt/vss/_work/1/s/node_modules/mocha/lib/runner.js:572:5)\n' +
@fluid-example/webflow:     '    at processImmediate (internal/timers.js:464:21)'
@fluid-example/webflow: }
```

**Comment by ChumpChief** [comment]
@hedasilv FYI

**Comment by hedasilv** [comment]
It seems that the error is caused from this call to `MongoManager`

https://github.com/microsoft/FluidFramework/blob/73fa08a48aeadb4aa334ddb1d55194c9da8206c4/server/routerlicious/packages/local-server/src/localDeltaConnectionServer.ts#L81

since `MongoManager`'s constructor uses `Lumberjack`. `Lumberjack` is this logging infra I added to r11s, and it needs some parameters - so when they are not provided, it logs that error message (it's been misleading as people seem to get confused and think that is an actual error, so I probably will have to change that later to a warning).

But the part that is confusing to me is that I try to setup `Lumberjack` a few lines before calling `MongoManager`: 
https://github.com/microsoft/FluidFramework/blob/73fa08a48aeadb4aa334ddb1d55194c9da8206c4/server/routerlicious/packages/local-server/src/localDeltaConnectionServer.ts#L71

After doing some experimentation, I found the cause for that error above to happen, but I don't know exactly why it happens. `Lumberjack` is based on a singleton implementation, so it builds on the fact that all calls to `Lumberjack` will be using the same instance. When I ran the `local-server` unit tests on the server side, I was able to verify that both `MongoManager` and the `LocalDeltaConnectionServer` used in `local-server` are using the same instance of the `Lumberjack` module (picture below). That means that once `LocalDeltaConnectionServer` sets up `Lumberjack`, `MongoManager` can use the same instance, which is already set up.

<img width="1445" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/41453887/157095685-4c91ba20-c897-4779-a3e6-081cbb3e6d37.png">

However, when the `local-server` is used from the examples folder, e.g. in the `table-document` example, I noticed that `LocalDeltaConnectionServer` uses an instance of `Lumberjack` singleton that is different than the `MongoManager` instance, as can be seen by the different IDs below.

<img width="1728" alt="MicrosoftTeams-image (3)" src="https://user-images.githubusercontent.com/41453887/157095833-6cba4a11-49dd-4037-8662-140689057fbc.png">

Since those are 2 different instances, even though `LocalDeltaConnectionServer` sets up `Lumberjack`, `MongoManager` cannot take advantage of that previous setup, which causes the error message to be logged.

Any ideas why that happens in the examples folder, but not under routerlicious/packages? Is there anything we could do to change that behavior - that is, make sure that once the code executes for the `table-document` example, all singleton instances be the same?

I chatted with @ChumpChief offline, who told me:

> The local driver is always used for a side-by-side mode and with session storage for persistence, for the purpose of testing fluid scenarios in a single tab. So we generally expect there to be two instances of all the driver stuff in the tab (or in the test). It's created in `getDocumentServiceFactory()` in packages\tools\webpack-fluid-loader\src\multiDocumentServiceFactory.ts, called by `createWebLoader()`, called twice in `start()` when running in side-by-side mode in packages\tools\webpack-fluid-loader\src\loader.ts
>
> That said, the `LocalDeltaConnectionServers` should be cached and reused in this flow, so there should only be one of those. Perhaps there's some issue that only appears when multiple `LocalDocumentServiceFactory` instances are created upon the same `LocalDeltaConnectionServer`?

I think that might be possible, but I believe the main problem is not that `LocalDeltaConnectionServer` is not reused, but rather, that when one "instance" of `LocalDeltaConnectionServer` is used, it calls components under `server-services-core`, and that particular instance of `server-services-core` module has a different `Lumberjack` than that of `LocalDeltaConnectionServer`, which is a behavior I don't observe on the server side.

I will continue looking into this, but let me know if you have any ideas.

**Comment by hedasilv** [comment]
Digging deeper, I was able to confirm this:

In routerlicious, when running Lumberjack, all packages use the file available here:

- /Users/hedasilv/Desktop/Code/FluidFrameworkCopy/server/routerlicious/packages/services-telemetry/dist/lumberjack.js

When running the examples, which fetch server packages from node_modules, each package - local-server and services-core - use Lumberjack from their own internal node_modules:


- **local-server:** /Users/hedasilv/Desktop/Code/FluidFrameworkCopy/node_modules/@fluidframework/server-local-server/node_modules/@fluidframework/server-services-telemetry/dist/lumberjack.js

- **services-core:** /Users/hedasilv/Desktop/Code/FluidFrameworkCopy/node_modules/@fluidframework/server-services-core/node_modules/@fluidframework/server-services-telemetry/dist/lumberjack.js

It looks like packages use nested node_modules when there is a version mismatch. And that seems to be the case...

- root node_modules/services-telemetry has this version: @fluidframework/server-services-telemetry@0.1034.0
- the one in the nested services-core and local-server has this version: @fluidframework/server-services-telemetry@0.1035.0-55212

I am now investigating why that is the case.

**Comment by hedasilv** [comment]
Digging further, it seems that `examples` and other client packages have been updated to use pre-release version 0.1035.x of server packages, but Tinylicious is still using 0.1034 (for example, Tinylicious still depends on version 0.1034 of server-services-telemetry).

As a result, when npm installs the dependencies, it puts server-services-telemetry @ 0.1034.0 into the "root" of the node_modules folder. Later, when the examples/local driver/etc try to use server packages @ 0.1035.x, and those depend on services-telemetry, npm puts services-telemetry @ 0.1035.x nested within each of the server packages inside of the root node_modules.

So the problem seems to be that due to dependency version mismatch between tinylicious and other client packages, the dependency tree on the root node_modules is not flat.

@ChumpChief mentioned 2 planned work items that should solve the problem:
* updating the tinylicious server dependency package version to 0.1035.x should fix the problem on the short term.
* longer term, we should move Tinylicious into the server build.

**Comment by ChumpChief** [comment]
For the first bullet, Tinylicious is restricted to using non-prerelease dependencies, so I'm checking on release plans for those dependencies.

For the second bullet, #6915 is tracking it.

**Comment by ChumpChief** [comment]
With #9494 we're up to date with latest server (0.1035.x) throughout the repo, but the issue persists.  @hedasilv can you please take another look?

**Comment by hedasilv** [comment]
@ChumpChief Even though that is the case, it seems that running `npm install` still causes nested node_modules dependencies. Example:
* @fluidframework
   * server-lambdas @0.1035.1000
   * server-local-server @0.1035.1000
      * node_modules/server-lambdas @0.1035.1000
      * node_modules/server-services-telemetry @0.1035.1000
   * server-services-core @0.1035.1000
      * node_modules/server-services-telemetry @0.1035.1000
   * node_modules/server-services-telemetry @0.1035.1000

As you can see, we have the root server-services-telemetry @0.1035.1000, but also nested server-services-telemetry at the same version within server-local-server and server-services-core. Note that it is not a behavior specific to the services-telemetry package, as server-lambdas (pictured above), and others, also show duplicate, nested packages.

The error message will persist until the node_modules tree is flattened, having only one server-services-telemetry package in the root. In the server lerna project, we don't have such an issue. So I think we probably need somebody from the client team to help us understand if there is a way to making the top-level node_modules flat - I unfortunately do not know how to make that happen.

Any ideas?

**Comment by ChumpChief** [comment]
I observe what you're seeing.  I notice that deleting/regenerating lerna-package-lock.json results in the flat structure expected (both in the file as well as in node_modules), though I don't know why that would be necessary to get the right result offhand.  I also observe that after doing this, the lumberjack errors go away.

Probably a more surgical modification of lerna-package-lock.json is the fastest way forward, though maybe this is indicative of some flaw in how we regenerate the file after dependency updates.

@curtisman do you have any ideas on why lerna-package-lock.json might end up with apparently-duplicative nested dependencies?

**Comment by curtisman** [comment]
That's a npm lock file behavior, where it doesn't update existing structure in the lock, even if it has become hoistable.
Likely, the previous version is at the root and the new version is nested.  And when you update the root version, the nested version remains.

Delete the nested entry in the lock and do a reinstall (delete the node_module and install).

**Comment by ChumpChief** [comment]
I put up a PR to do that - I worry this will be a recurring problem given our current structure/release approach though, as the tinylicious release will always lag the server release.  I think avoiding this will require client packages to defer taking new server packages until they can simultaneously take the new tinylicious that includes those packages too, which shouldn't really be a requirement from a dependency perspective.

This probably would be addressed by #6915, but until then this seems likely to recur.

I wonder if there also might be options to consider in the server packages to become more robust to this situation?  I am not familiar with the lumberjack integration but perhaps there's other strategies to ensure we're sharing the setup appropriately?

**Comment by tylerbutler** [comment]
> Delete the nested entry in the lock and do a reinstall (delete the node_module and install).

Would deleting the lockfiles and running install also work? Editing lockfiles is always error-prone in my experience.

**Comment by hedasilv** [comment]
One thing we could do in `Lumberjack` (which I might have forgotten to do, apologies about that) is prevent any error logging if the code is running in "test" mode. Which I believe would apply to all the use-case scenarios involving Tinylicious, local-server, etc. The error message reported above is nothing but a message, and not a real error blocking the tests. So, suppressing the message might suffice in this case (we only care about `Lumberjack` functionality in actual server code - so even if we don't fix the root causing issue about the nested node_modules, it might already help in the context of local-server). However, in case this issue has impact on any other packages as well, those would have to be fixed separately.

Let me look into how feasible it is to turn on/off `Lumberjack` error logging based on the context/environment.
