### ISSUE TITLE
PropertyDDS concurrent insert of the same key to Map

### ISSUE THREAD

**Issue by milanro** [microsoft/FluidFramework#9381]
## Describe the bug

- We create map of complex type containing 'person' attribute under the property path W_0.0249997558655648.words and commit.
- On 2 clients we add complex value containing the sub-attribute person under the same key but do not commit.
- On both clients we have uncommitted path W_0.0249997558655648".words[0].person 
- We commit on Client 1 and then on Client 2
- We change on the Client 1 value of W_0.0249997558655648".words[0].person and commit
- This change is broadcasted to Client 2
- We change on the Client 2 value of W_0.0249997558655648".words[0].person and commit
- The change is not broadcasted and exception is thrown

    Uncaught Error: PR-003: Invalid path in ChangeSet: "W_0.0249997558655648.".words[0].person. Making primitive value reversible.
        at _recursivelyBuildReversibleChangeSet (main.591ee344ba70f10857c4.js:157749:27)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163725:13)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163914:25)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163901:25)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163914:25)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163901:25)

The exception is thrown in the code packages/property-changeset/src/changeset.ts in the method _recursivelyBuildReversibleChangeSet where the value of in_context.getPropertyContainerType() is "template" and in_context.getUserData().parallelState is undefined.

#### Clone Forked Repository 
git clone [git@github.com:dstanesc/FluidFramework.git](mailto:git@github.com:dstanesc/FluidFramework.git) FluidFramework.Debug

#### Build Forked Repository 
cd FluidFramework.Debug
git checkout pdds-words-app
npm install
npm run build:fast

#### Start Tinylicious in another shell
npx tinylicious

#### Start Application
cd experimental/PropertyDDS/examples/propdbg
npm start

#### Perform Test
Open 2 clients for collaboration​
**Client 1​**

-         Create Words​
-         Commit​
-         Add Word​

**Client 2​**

-         Add Word​

**Client 1​**

-         Commit​

**Client 2​**

-         Commit​

**Client 1 ​**

-         -C​

**Client 2​**

-         -C​

    **Exception at Client 2**
    Uncaught Error: PR-003: Invalid path in ChangeSet: "W_0.3359562026939633".words[0].person. Making primitive value reversible.
        at _recursivelyBuildReversibleChangeSet (main.591ee344ba70f10857c4.js:157749:27)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163725:13)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163914:25)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163901:25)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163914:25)
        at processChange (main.591ee344ba70f10857c4.js:163788:13)
        at _traverseChangeSetRecursively (main.591ee344ba70f10857c4.js:163901:25)

### Expected behavior
Pressing -C at Client 2 should change the local value of the PERSON column and that value should be broadcasted to Client 2 PERSON column.

### Video
https://user-images.githubusercontent.com/30476743/157088417-4c93c643-02ea-45f2-a7d0-ef7482ce6a8e.mp4

**Comment by evaliyev** [comment]
Hey @milanro,
There are 2 underlying issues for this big. 

First, SharedPropertyTree is not updating the local changeSet correctly. This leads to incorrect property state updates later on. This issue is resolved in https://github.com/microsoft/FluidFramework/pull/9692

The second issue stems from the fact Client 1 and Client 2 try to insert two objects under the same key in the words map in https://github.com/dstanesc/FluidFramework/blob/pdds-words-app/experimental/PropertyDDS/examples/propdbg/src/words.ts#L38. Insertion results in conflict that SharedPropertyTree is not equipped to resolve. A possible solution would be use unique keys e.g. `const wordId = uuid()`.

Implementation of conflict resolution would require a callback from a client to specify how exactly the conflict should be resolved.  Considering, that SharedPropertyTree can be updated by multiple different clients with different implementations, the callback code needs to be exactly the same, which could get tricky. At the moment, no decision has been made on this

**Comment by milanro** [comment]
Hi @evaliyev , thank you for the bug exploration and clarification. If I understand well, the proposed solution at  #9692 will fix the inconsistency among clients. Concerning the second issue, it is clear that there is no conflict resolution facility. I suppose that the conflict is resolved automatically by LWW strategy which is expected behavior and perfectly ok with us.
