### ISSUE TITLE
ContainerClose and NoJoinOp errors during scalability testing

### ISSUE THREAD

**Issue by sharmakhushboo** [microsoft/FluidFramework#9699]
## Describe the bug
We are doing scalability tests against FRS. The test with 2500 clients submitting 200 ops each, starts erroring out with the 'ContainerClose' and 'NoJoinOp' errors half way through the test. The impact of these errors is that the clients stop sending ops and disconnect.

I was also seeing ‘connectedStateRejected’ error before but I resolved this by increasing the maxClientLeaveWaitTime to about 15mins (Default is 5mins). Apart from this, there are also summary related errors but I’m ignoring these right now as another feature crew is working on fixing summary scalability. Right now our focus is to scale the ordering flow.

Another thing to note is that from FRS side, there are no errors in the ordering flow. So, I believe it is timing out somewhere in the pipeline? I have increased all the timeouts for nginx and also the idleTimeout for load balancers in AKS. Also, we have enough CPU/Memory on server side to take the load. Now, I'm looking for some more leads. 

I see here https://github.com/microsoft/FluidFramework/pull/7393 that switching to read mode might help but since clients don't set the connection mode, I'm not sure how to go about this.

### To Reproduce
1. Go to [stress test tool](https://github.com/sharmakhushboo/FRSSamples/tree/781a8fe10df026e598a53ab0ce288d02e6bd3117/tests/stress)
2. Run the tool with 2500 clients.

### Expected behavior
clients should successfully submit all the ops.

### Logs
I can provide more logs if necessary.

`{"eventName":"fluid:telemetry:Container:ContainerClose","category":"error","stack":"Error\n    at Object.assert (/FRSSamples/tests/stress/node_modules/@fluidframework/container-loader/node_modules/@fluidframework/common-utils/dist/assert.js:17:15)\n    at ConnectionStateHandler.receivedConnectEvent (/FRSSamples/tests/stress/node_modules/@fluidframework/container-loader/dist/connectionStateHandler.js:151:28)\n    at DeltaManager.<anonymous> (/FRSSamples/tests/stress/node_modules/@fluidframework/container-loader/dist/container.js:1030:41)\n    at DeltaManager.emit (events.js:412:35)\n    at DeltaManager.connectHandler (/FRSSamples/tests/stress/node_modules/@fluidframework/container-loader/dist/deltaManager.js:198:14)\n    at Object.connectHandler (/FRSSamples/tests/stress/node_modules/@fluidframework/container-loader/dist/deltaManager.js:60:50)\n    at ConnectionManager.setupNewSuccessfulConnection (/FRSSamples/tests/stress/node_modules/@fluidframework/container-loader/dist/connectionManager.js:532:20)\n    at ConnectionManager.connectCore (/FRSSamples/tests/stress/node_modules/@fluidframework/container-loader/dist/connectionManager.js:413:14)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)","error":"0x2a6","errorType":"genericError","fluidErrorCode":"-","fatalConnectError":true,"untrustedOrigin":1,"message":"0x2a6","errorInstanceId":"659fe6ae-147f-4bcc-b868-709445106bd3","clientType":"interactive","containerId":"60dff096-9437-494f-9a10-3f3599c90786","docId":"76030139-4313-4150-aaab-8182ebf7b64f","containerAttachState":"Attached","containerLifecycleState":"closing","containerConnectionState":"Disconnected","dmInitialSeqNumber":0,"dmLastProcessedSeqNumber":352,"dmLastKnownSeqNumber":383,"containerLoadedFromVersionId":"bBwAAAAAHAAAA","dmLastMsqSeqNumber":352,"dmLastMsqSeqTimestamp":1648682952322,"dmLastMsqSeqClientId":"7ae72b3e-f391-4479-abf1-65eac34ce79c","connectionStateDuration":2.86203800002113,"loaderId":"4c916fb3-24de-4df1-ae8b-d284edf6c2b2","loaderVersion":"0.59.1000-58058"}`

`{"eventName":"fluid:telemetry:DeltaManager:NoJoinOp","duration":45000,"fetchReason":"DocumentOpen_fetch","lastQueuedSequenceNumber":0,"lastProcessedSequenceNumber":0,"lastObserved":300,"clientId":"84e6a731-80d3-437e-9f77-e3a8aad5186d","mode":"write","connectionInitialOpsFrom":195,"connectionInitialOpsTo":206,"connectionLastQueuedSequenceNumber":0,"connectionLastObservedSeqNumber":205,"pendingOps":106,"pendingFirst":195,"haveHandler":true,"inboundLength":0,"inboundPaused":false,"category":"error","clientType":"noninteractive/summarizer","containerId":"189ceebc-6a5e-4e4e-bbb4-8fbed118627f","docId":"9868cc30-9057-4d9d-8c8f-20340ed43377","containerAttachState":"Attached","containerLifecycleState":"loaded","containerConnectionState":"Connecting","dmInitialSeqNumber":0,"dmLastProcessedSeqNumber":0,"dmLastKnownSeqNumber":300,"containerLoadedFromVersionId":"bBwAAAAAHAAAA","connectionStateDuration":45001.38924100017,"loaderId":"c2cb436f-59f5-4773-880d-88a0cdcb8a49","loaderVersion":"0.59.1000-58058"}`

**Comment by vladsud** [comment]
This error means that client did not receive its own join op within timeout (45 seconds) after connecting as "write" client.
Historically, there were a lot of issues in op pipeline that we worked hard to fix.
Usually, these errors correlate with OpRoundtripTime errors (category = "error", which signifies it takes longer than 5 seconds for op to be acked). Hard to say where the issues are, but the last time I looked at ODSP stress tests and FFX production telemetry there were relatively very few of such errors (compared to usage, for example 7 days of prod telemetry - 440 hits out of 3.2M sessions, 170 out of 2.4M sessions when excluding summarizer sessions that have the problem described below).

This is really bad from customer POV, as local changes are not propagated to service, and thus there is great chance of data loss.

That all said, there is one other angle to consider. For scenarios that do not specify custom ILoaderOptions (like FFX does, where they control when initial socket connection happens, which is delayed until container boots fully and renders), we start establishing "write" connection as part of booting container. If container load takes long time, but completes within these 45 seconds, then this event might fire simply because we were not processing ops for most of this timeframe (as container was loading). We observed these issues in ODSP stress tests, and the right fix here is to change default connection mode to "read", which is not easy (as most of or tests start failing). This is tracked via https://github.com/microsoft/FluidFramework/issues/7772
This is the reason for most errors we see in ODSP stress tests, that are using default settings. NUmber of them is not large (based on my memory), and they mostly signify network issues (and retries) around loading snapshot.

**Comment by vladsud** [comment]
You would need to understand better why you are seeing these issues, i.e. which bucket it belongs and root cause it, as well as understand severity and how that shows up to (potential) user (scenarios). I.e. is this more a problem of slow boot, or is this a problem of op not arriving in reasonable time.

**Comment by vladsud** [comment]
As for maxClientLeaveWaitTime, this signifies we waited too long to receive our own leave op from previous connection. I'd suggest having separate bug for that.

**Comment by vladsud** [comment]
Based on looking at the logs for single run, I'd suggest focusing first on the issue of really wide distribution (and thus very long tale) for op rountrip times. Average, P90 are in unacceptable territory, needs to see impartments in 5-10x range before we can re-evaluate these events.

**Comment by sharmakhushboo** [comment]
NoJoinOpErrors resolved by disabling perMessageDeflate. 
PR: https://github.com/microsoft/FluidFramework/pull/10593
